1 Command: Command-line option -outvars is deprecated: please use -head instead
2 Command: Command-line option -vars is deprecated: please use -head instead
3 Command: Procedure q_lskum_d understood as q_lskum_mod_diff.q_lskum_d
4 initial_conditions_d: (DF03) variable rank is used before initialized
5 restart_sol: (TC62) Undeclared type: unknowntype
6 restart_sol: (TC24) Wrong number of dimensions for array itos: 1 expected, and 2 given
7 restart_sol: (TC12) Array index is expected to be integer, and is here unknowntype
8 restart_sol: (DF03) variable proc is used before initialized
9 func_delta_d: (TC19) Equality test on reals is not reliable
10 func_delta_d: (TC19) Equality test on reals is not reliable
11 conserved_vector_ubar_d: (TC19) Equality test on reals is not reliable
12 conserved_vector_ubar_d: (TC19) Equality test on reals is not reliable
13 conserved_vector_ubar_d: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
14 conserved_vector_ubar_d: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
15 flux_quad_gxi_d: (TC19) Equality test on reals is not reliable
16 flux_quad_gxi_d: (TC19) Equality test on reals is not reliable
17 flux_quad_gxi_d: (TC19) Equality test on reals is not reliable
18 flux_quad_gxi_d: (TC19) Equality test on reals is not reliable
19 flux_quad_gxi_d: (TC33) External procedure derf is not declared
20 flux_quad_gxi_d: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
21 flux_quad_gxi_d: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
22 flux_quad_gxii_d: (TC19) Equality test on reals is not reliable
23 flux_quad_gxii_d: (TC19) Equality test on reals is not reliable
24 flux_quad_gxii_d: (TC19) Equality test on reals is not reliable
25 flux_quad_gxii_d: (TC19) Equality test on reals is not reliable
26 flux_quad_gxii_d: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
27 flux_quad_gxii_d: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
28 flux_quad_gxiii_d: (TC19) Equality test on reals is not reliable
29 flux_quad_gxiii_d: (TC19) Equality test on reals is not reliable
30 flux_quad_gxiii_d: (TC19) Equality test on reals is not reliable
31 flux_quad_gxiii_d: (TC19) Equality test on reals is not reliable
32 flux_quad_gxiii_d: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
33 flux_quad_gxiii_d: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
34 flux_quad_gxiv_d: (TC19) Equality test on reals is not reliable
35 flux_quad_gxiv_d: (TC19) Equality test on reals is not reliable
36 flux_quad_gxiv_d: (TC19) Equality test on reals is not reliable
37 flux_quad_gxiv_d: (TC19) Equality test on reals is not reliable
38 flux_quad_gxiv_d: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
39 flux_quad_gxiv_d: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
40 flux_gxp_d: (TC19) Equality test on reals is not reliable
41 flux_gxp_d: (TC19) Equality test on reals is not reliable
42 flux_gxp_d: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
43 flux_gxn_d: (TC19) Equality test on reals is not reliable
44 flux_gxn_d: (TC19) Equality test on reals is not reliable
45 flux_gxn_d: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
46 flux_gyp_d: (TC19) Equality test on reals is not reliable
47 flux_gyp_d: (TC19) Equality test on reals is not reliable
48 flux_gyp_d: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
49 flux_gyn_d: (TC19) Equality test on reals is not reliable
50 flux_gyn_d: (TC19) Equality test on reals is not reliable
51 flux_gyn_d: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
52 (DF05) External routine derf, called by (flux_quad_gxi_d flux_quad_gxi flux_quad_gxii_d flux_quad_gxii flux_quad_gxiii_d flux_quad_gxiii flux_quad_gxiv_d flux_quad_gxiv flux_gxp_d flux_gxp flux_gxn_d flux_gxn flux_gyp_d flux_gyp flux_gyn_d flux_gyn conserved_vector_ubar_d conserved_vector_ubar), is assumed default In:.1. and Out:.11
53 data_structure_mod_diff_diff: (DD28) Save statement may save extra variables, please use "save::varname" 
