!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.14 (r7079) -  5 Oct 2018 09:56
!
MODULE OBJECTIVE_FUNCTION_MOD_DIFF
  USE DATA_STRUCTURE_MOD_DIFF
  USE COMPUTE_FORCE_COEFFS_MOD_DIFF
  USE COMPUTE_ENTROPY_MOD_DIFF
  USE COMPUTE_ENSTROPHY_MOD_DIFF
  IMPLICIT NONE

CONTAINS
!  Differentiation of objective_function in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: total_enstrophy cd cl cm total_entropy
!                point.vorticity_sqr
!   with respect to varying inputs: point.x point.y point.nx point.ny
!                point.prim point.vorticity_sqr
  SUBROUTINE OBJECTIVE_FUNCTION_D()
    IMPLICIT NONE
    CALL COMPUTE_CL_CD_CM_D()
    CALL COMPUTE_ENTROPY_D()
    CALL COMPUTE_ENSTROPHY_D()
  END SUBROUTINE OBJECTIVE_FUNCTION_D

  SUBROUTINE OBJECTIVE_FUNCTION()
    IMPLICIT NONE
    CALL COMPUTE_CL_CD_CM()
    CALL COMPUTE_ENTROPY()
    CALL COMPUTE_ENSTROPHY()
  END SUBROUTINE OBJECTIVE_FUNCTION

END MODULE OBJECTIVE_FUNCTION_MOD_DIFF

