1 Command: Command-line option -outvars is deprecated: please use -head instead
2 Command: Command-line option -vars is deprecated: please use -head instead
3 Command: Procedure q_lskum understood as q_lskum_mod.q_lskum
4 conserved_vector_ubar: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
5 conserved_vector_ubar: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
6 flux_quad_gxi: (TC33) External procedure derf is not declared
7 flux_quad_gxi: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
8 flux_quad_gxi: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
9 flux_quad_gxii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
10 flux_quad_gxii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
11 flux_quad_gxiii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
12 flux_quad_gxiii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
13 flux_quad_gxiv: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
14 flux_quad_gxiv: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
15 flux_quad_gxi_d: (TC19) Equality test on reals is not reliable
16 flux_quad_gxi_d: (TC19) Equality test on reals is not reliable
17 flux_quad_gxi_d: (TC19) Equality test on reals is not reliable
18 flux_quad_gxi_d: (TC19) Equality test on reals is not reliable
19 flux_quad_gxii_d: (TC19) Equality test on reals is not reliable
20 flux_quad_gxii_d: (TC19) Equality test on reals is not reliable
21 flux_quad_gxii_d: (TC19) Equality test on reals is not reliable
22 flux_quad_gxii_d: (TC19) Equality test on reals is not reliable
23 flux_quad_gxiii_d: (TC19) Equality test on reals is not reliable
24 flux_quad_gxiii_d: (TC19) Equality test on reals is not reliable
25 flux_quad_gxiii_d: (TC19) Equality test on reals is not reliable
26 flux_quad_gxiii_d: (TC19) Equality test on reals is not reliable
27 flux_quad_gxiv_d: (TC19) Equality test on reals is not reliable
28 flux_quad_gxiv_d: (TC19) Equality test on reals is not reliable
29 flux_quad_gxiv_d: (TC19) Equality test on reals is not reliable
30 flux_quad_gxiv_d: (TC19) Equality test on reals is not reliable
31 flux_gxp: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
32 flux_gxn: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
33 flux_gyp: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
34 flux_gyn: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
35 flux_gxp_d: (TC19) Equality test on reals is not reliable
36 flux_gxp_d: (TC19) Equality test on reals is not reliable
37 flux_gxn_d: (TC19) Equality test on reals is not reliable
38 flux_gxn_d: (TC19) Equality test on reals is not reliable
39 flux_gyp_d: (TC19) Equality test on reals is not reliable
40 flux_gyp_d: (TC19) Equality test on reals is not reliable
41 flux_gyn_d: (TC19) Equality test on reals is not reliable
42 flux_gyn_d: (TC19) Equality test on reals is not reliable
43 (DF05) External routine derf, called by (flux_quad_gxi flux_quad_gxii flux_quad_gxiii flux_quad_gxiv flux_quad_gxi_d flux_quad_gxii_d flux_quad_gxiii_d flux_quad_gxiv_d flux_gxp flux_gxn flux_gyp flux_gyn flux_gxp_d flux_gxn_d flux_gyp_d flux_gyn_d conserved_vector_ubar), is assumed default In:.1. and Out:.11
44 data_structure_mod_diff: (DD28) Save statement may save extra variables, please use "save::varname" 
