!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.14 (r7079) -  5 Oct 2018 09:56
!
MODULE FPI_SOLVER_MOD_DIFF
  USE DATA_STRUCTURE_MOD_DIFF
  USE FLUX_RESIDUAL_MOD_DIFF
  USE STATE_UPDATE_MOD_DIFF
  USE Q_VARIABLES_MOD_DIFF
  USE OBJECTIVE_FUNCTION_MOD_DIFF
  IMPLICIT NONE

CONTAINS
!  Differentiation of fpi_solver in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: total_enstrophy cd cl cm total_entropy
!                point.x point.y point.nx point.ny point.prim point.prim_old
!                point.flux_res point.q point.dq point.qm point.vorticity_sqr
!                point.delta
!   with respect to varying inputs: point.x point.y point.nx point.ny
!                point.prim point.prim_old point.flux_res point.q
!                point.dq point.qm point.vorticity_sqr point.delta
  SUBROUTINE FPI_SOLVER_B(t)
    IMPLICIT NONE
    INTEGER :: t, i, rk
    INTRINSIC DSQRT
    INTRINSIC DLOG10
    DO i=1,local_points
      point%prim_old(:, i) = point%prim(:, i)
    END DO
    CALL FUNC_DELTA()
! Perform 4-stage, 3-order SSPRK update
    DO rk=1,4
      CALL PUSHREAL8ARRAY(point%q, 4*max_points)
      CALL EVAL_Q_VARIABLES()
      CALL PUSHREAL8ARRAY(point%qm, 2*4*max_points)
      CALL PUSHREAL8ARRAY(point%dq, 2*4*max_points)
      CALL EVAL_Q_DERIVATIVES()
      CALL PUSHREAL8ARRAY(point%flux_res, 4*max_points)
      CALL CAL_FLUX_RESIDUAL()
      CALL PUSHREAL8ARRAY(point%prim, 4*max_points)
      CALL STATE_UPDATE(rk)
    END DO
    CALL OBJECTIVE_FUNCTION_B()
    DO rk=4,1,-1
      CALL POPREAL8ARRAY(point%prim, 4*max_points)
      CALL STATE_UPDATE_B(rk)
      CALL POPREAL8ARRAY(point%flux_res, 4*max_points)
      CALL CAL_FLUX_RESIDUAL_B()
      CALL POPREAL8ARRAY(point%dq, 2*4*max_points)
      CALL POPREAL8ARRAY(point%qm, 2*4*max_points)
      CALL EVAL_Q_DERIVATIVES_B()
      CALL POPREAL8ARRAY(point%q, 4*max_points)
      CALL EVAL_Q_VARIABLES_B()
    END DO
    CALL FUNC_DELTA_B()
    DO i=local_points,1,-1
      pointb%prim(:, i) = pointb%prim(:, i) + pointb%prim_old(:, i)
      pointb%prim_old(:, i) = 0.0_8
    END DO
  END SUBROUTINE FPI_SOLVER_B

  SUBROUTINE FPI_SOLVER(t)
    IMPLICIT NONE
    INTEGER :: t, i, rk
    INTRINSIC DSQRT
    INTRINSIC DLOG10
    DO i=1,local_points
      point%prim_old(:, i) = point%prim(:, i)
    END DO
    CALL FUNC_DELTA()
! Perform 4-stage, 3-order SSPRK update
    DO rk=1,4
      CALL EVAL_Q_VARIABLES()
      CALL EVAL_Q_DERIVATIVES()
      CALL CAL_FLUX_RESIDUAL()
      CALL STATE_UPDATE(rk)
    END DO
    CALL OBJECTIVE_FUNCTION()
    res_new = DSQRT(sum_res_sqr)/plen
    IF (t .LE. 2) THEN
      res_old = res_new
      residue = 0.d0
    ELSE
      residue = DLOG10(res_new/res_old)
    END IF
  END SUBROUTINE FPI_SOLVER

END MODULE FPI_SOLVER_MOD_DIFF

