!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.14 (r7259) - 18 Jan 2019 09:36
!
MODULE COMPUTE_FORCE_COEFFS_MOD_DIFF
!#include <petsc/finclude/petscsys.h>
  USE DATA_STRUCTURE_MOD_DIFF
  USE PETSC_DATA_STRUCTURE_MOD
  IMPLICIT NONE

CONTAINS
  SUBROUTINE COMPUTE_CL_CD_CM()
    IMPLICIT NONE
    INTEGER :: i, j, k
    INTEGER :: l, m, r
    REAL*8 :: cp, temp
    REAL*8 :: lx, ly, mx, my, rx, ry
    REAL*8 :: ds1, ds2, ds
    REAL*8, DIMENSION(shapes) :: h, v, pitch_mom
    REAL*8, DIMENSION(shapes) :: lcl, lcd, lcm
    REAL*8 :: nx, ny
    CHARACTER(len=64) :: cp_file
    CHARACTER(len=10) :: itos
    INTRINSIC TRIM
    INTRINSIC DSQRT
    INTRINSIC DCOS
    INTRINSIC DSIN
! PetscErrorCode :: ierr
    cp_file = 'cp/'//'cp-file'
    IF (proc .GT. 1) cp_file = 'cp/'//'cp-file'//TRIM(itos(4, rank))
    OPEN(unit=201, file=trim(cp_file), form='FORMATTED', status=&
&  'REPLACE', action='WRITE') 
!if(rank==0) OPEN(UNIT=202,FILE='clcdcm')
    temp = 0.5d0*rho_inf*mach*mach
    h = 0.d0
    v = 0.d0
    pitch_mom = 0.0d0
    DO j=1,shape_points
      m = shape_points_index(j)
      r = point%right(m)
      l = point%left(m)
      lx = point%x(l)
      ly = point%y(l)
      mx = point%x(m)
      my = point%y(m)
      rx = point%x(r)
      ry = point%y(r)
      ds1 = (mx-lx)**2 + (my-ly)**2
      ds1 = DSQRT(ds1)
      ds2 = (rx-mx)**2 + (ry-my)**2
      ds2 = DSQRT(ds2)
      ds = 0.5d0*(ds1+ds2)
      nx = point%nx(m)
      ny = point%ny(m)
      cp = point%prim(4, m) - pr_inf
      cp = -(cp/temp)
      WRITE(201, *) point%flag_2(m), point%x(m), cp
      h(point%flag_2(m)) = h(point%flag_2(m)) + cp*nx*ds
      v(point%flag_2(m)) = v(point%flag_2(m)) + cp*ny*ds
      pitch_mom(point%flag_2(m)) = pitch_mom(point%flag_2(m)) + (-(cp*ny&
&       *ds*(mx-0.25d0))+cp*nx*ds*my)
    END DO
    lcl = v*DCOS(theta) - h*DSIN(theta)
    lcd = h*DCOS(theta) + v*DSIN(theta)
    lcm = pitch_mom
! call MPI_Reduce(lCl, Cl , shapes, MPI_DOUBLE, MPI_SUM, 0, &
!         & PETSC_COMM_WORLD, ierr)
! call MPI_Reduce(lCd, Cd , shapes, MPI_DOUBLE, MPI_SUM, 0, &
!         & PETSC_COMM_WORLD, ierr)
! call MPI_Reduce(lCm, Cm , shapes, MPI_DOUBLE, MPI_SUM, 0, &
!         & PETSC_COMM_WORLD, ierr)
! if(rank == 0) then
!         do j = 1, shapes
!                 write(*,'(i4,3e30.20)') j, Cl, Cd, Cm
!         end do
! end if
    CLOSE(unit=201) 
  END SUBROUTINE COMPUTE_CL_CD_CM

END MODULE COMPUTE_FORCE_COEFFS_MOD_DIFF

