1 Command: Command-line option -vars is deprecated: please use -head instead
2 Command: Command-line option -outvars is deprecated: please use -head instead
3 Command: Procedure q_lskum understood as q_lskum_mod.q_lskum
4 q_lskum_mod: (DD15) Module initial_conditions_mod is not defined
5 q_lskum_mod: (DD15) Module ieee_arithmetic is not defined
6 q_lskum: (TC33) External procedure ieee_is_nan is not declared
7 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%delta
8 q_lskum: (AD12) User help requested: unknown dimension 3 of array *point%temp
9 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%temp
10 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%temp
11 q_lskum: (AD12) User help requested: unknown dimension 3 of array *point%ddq
12 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%ddq
13 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%ddq
14 q_lskum: (AD12) User help requested: unknown dimension 3 of array *point%qm
15 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%qm
16 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%qm
17 q_lskum: (AD12) User help requested: unknown dimension 3 of array *point%dq
18 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%dq
19 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%dq
20 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%q
21 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%q
22 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%flux_res
23 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%flux_res
24 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%prim_old
25 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%prim_old
26 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%prim
27 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%prim
28 (DF05) External routine ieee_is_nan, called by (q_lskum), is assumed default In:.1. and Out:.11
29 fpi_solver_mod: (DD15) Module post_processing_mod is not defined
30 fpi_solver: (TC33) External procedure print_primal_output is not declared
31 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%q
32 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%q
33 fpi_solver: (AD12) User help requested: unknown dimension 3 of array *point%dq
34 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%dq
35 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%dq
36 fpi_solver: (AD12) User help requested: unknown dimension 3 of array *point%ddq
37 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%ddq
38 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%ddq
39 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%flux_res
40 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%flux_res
41 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%prim
42 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%prim
43 (DF05) External routine print_primal_output, called by (fpi_solver), is assumed default In:. and Out:.
44 state_update_mod: (DD15) Module petsc_data_structure_mod is not defined
45 cal_flux_residual: (AD12) User help requested: unknown dimension 1 of array *point%flux_res
46 cal_flux_residual: (AD12) User help requested: unknown dimension 1 of array *point%flux_res
47 conserved_vector_ubar: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
48 conserved_vector_ubar: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
49 generate_connectivity_mod: (DD15) Module petsc_data_structure_mod is not defined
50 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
51 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
52 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
53 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
54 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
55 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
56 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
57 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
58 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
59 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
60 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
61 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
62 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
63 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
64 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
65 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
66 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
67 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
68 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
69 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
70 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
71 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
72 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
73 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
74 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
75 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
76 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
77 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
78 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
79 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
80 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
81 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
82 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
83 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
84 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
85 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
86 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
87 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
88 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
89 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
90 eval_q_derivatives: (AD12) User help requested: unknown dimension 1 of array temp
91 eval_q_derivatives: (AD12) User help requested: unknown dimension 1 of array temp
92 eval_q_double_derivatives: (AD12) User help requested: unknown dimension 1 of array temp
93 eval_q_double_derivatives: (AD12) User help requested: unknown dimension 1 of array temp
94 eval_q_double_derivatives: (AD12) User help requested: unknown dimension 1 of array temp
95 eval_q_double_derivatives: (AD12) User help requested: unknown dimension 1 of array temp
96 flux_gxp: (TC33) External procedure derf is not declared
97 flux_gxp: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
98 flux_gxn: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
99 flux_gyp: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
100 flux_gyn: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
101 flux_quad_gxi: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
102 flux_quad_gxi: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
103 flux_quad_gxii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
104 flux_quad_gxii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
105 flux_quad_gxiii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
106 flux_quad_gxiii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
107 flux_quad_gxiv: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
108 flux_quad_gxiv: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
109 (DF05) External routine derf, called by (flux_gxp flux_gxn flux_gyp flux_gyn conserved_vector_ubar flux_quad_gxi flux_quad_gxii flux_quad_gxiii flux_quad_gxiv), is assumed default In:.1. and Out:.11
110 compute_force_coeffs_mod: (DD15) Module petsc_data_structure_mod is not defined
111 compute_cl_cd_cm: (TC24) Wrong number of dimensions for array itos: 1 expected, and 2 given
112 compute_entropy_mod: (DD15) Module petsc_data_structure_mod is not defined
113 compute_entropy: (TC20) Variable mpi_double is not declared
114 compute_entropy: (TC20) Variable mpi_sum is not declared
115 compute_entropy: (TC20) Variable petsc_comm_world is not declared
116 compute_entropy: (TC20) Variable ierr is not declared
117 stagnation_values_mod: (DD15) Module petsc_data_structure_mod is not defined
118 data_structure_mod: (DD28) Save statement may save extra variables, please use "save::varname" 
