!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.14 (r7079) -  5 Oct 2018 09:56
!
MODULE COMPUTE_FORCE_COEFFS_MOD_DIFF
  USE DATA_STRUCTURE_MOD_DIFF
  IMPLICIT NONE

CONTAINS
!  Differentiation of compute_cl_cd_cm in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: cd cl cm
!   with respect to varying inputs: theta point.prim
  SUBROUTINE COMPUTE_CL_CD_CM_D()
    IMPLICIT NONE
    INTEGER :: i, j, k
    INTEGER :: l, m, r
    REAL*8 :: cp, temp
    REAL*8 :: cpd
    REAL*8 :: lx, ly, mx, my, rx, ry
    REAL*8 :: ds1, ds2, ds
    REAL*8, DIMENSION(shapes) :: h, v, pitch_mom
    REAL*8, DIMENSION(shapes) :: hd, vd, pitch_momd
    REAL*8 :: nx, ny
    INTRINSIC DSQRT
    INTRINSIC DCOS
    INTRINSIC DSIN
    temp = 0.5d0*rho_inf*mach*mach
    h = 0.d0
    v = 0.d0
    pitch_mom = 0.0d0
    hd = 0.0_8
    vd = 0.0_8
    pitch_momd = 0.0_8
    DO j=1,shape_points
      m = shape_points_index(j)
      r = point%right(m)
      l = point%left(m)
      lx = point%x(l)
      ly = point%y(l)
      mx = point%x(m)
      my = point%y(m)
      rx = point%x(r)
      ry = point%y(r)
      ds1 = (mx-lx)**2 + (my-ly)**2
      ds1 = DSQRT(ds1)
      ds2 = (rx-mx)**2 + (ry-my)**2
      ds2 = DSQRT(ds2)
      ds = 0.5d0*(ds1+ds2)
      nx = point%nx(m)
      ny = point%ny(m)
      cpd = pointd%prim(4, m)
      cp = point%prim(4, m) - pr_inf
      cpd = -(cpd/temp)
      cp = -(cp/temp)
      hd(point%flag_2(m)) = hd(point%flag_2(m)) + nx*ds*cpd
      h(point%flag_2(m)) = h(point%flag_2(m)) + cp*nx*ds
      vd(point%flag_2(m)) = vd(point%flag_2(m)) + ny*ds*cpd
      v(point%flag_2(m)) = v(point%flag_2(m)) + cp*ny*ds
      pitch_momd(point%flag_2(m)) = pitch_momd(point%flag_2(m)) + nx*ds*&
&       my*cpd - ny*ds*(mx-0.25d0)*cpd
      pitch_mom(point%flag_2(m)) = pitch_mom(point%flag_2(m)) + (-(cp*ny&
&       *ds*(mx-0.25d0))+cp*nx*ds*my)
    END DO
    cld = vd*DCOS(theta) - v*thetad*DSIN(theta) - hd*DSIN(theta) - h*&
&     thetad*DCOS(theta)
    cl = v*DCOS(theta) - h*DSIN(theta)
    cdd = hd*DCOS(theta) - h*thetad*DSIN(theta) + vd*DSIN(theta) + v*&
&     thetad*DCOS(theta)
    cd = h*DCOS(theta) + v*DSIN(theta)
    clcd = cl/cd
    cmd = pitch_momd
    cm = pitch_mom
  END SUBROUTINE COMPUTE_CL_CD_CM_D

  SUBROUTINE COMPUTE_CL_CD_CM()
    IMPLICIT NONE
    INTEGER :: i, j, k
    INTEGER :: l, m, r
    REAL*8 :: cp, temp
    REAL*8 :: lx, ly, mx, my, rx, ry
    REAL*8 :: ds1, ds2, ds
    REAL*8, DIMENSION(shapes) :: h, v, pitch_mom
    REAL*8 :: nx, ny
    INTRINSIC DSQRT
    INTRINSIC DCOS
    INTRINSIC DSIN
    temp = 0.5d0*rho_inf*mach*mach
    h = 0.d0
    v = 0.d0
    pitch_mom = 0.0d0
    DO j=1,shape_points
      m = shape_points_index(j)
      r = point%right(m)
      l = point%left(m)
      lx = point%x(l)
      ly = point%y(l)
      mx = point%x(m)
      my = point%y(m)
      rx = point%x(r)
      ry = point%y(r)
      ds1 = (mx-lx)**2 + (my-ly)**2
      ds1 = DSQRT(ds1)
      ds2 = (rx-mx)**2 + (ry-my)**2
      ds2 = DSQRT(ds2)
      ds = 0.5d0*(ds1+ds2)
      nx = point%nx(m)
      ny = point%ny(m)
      cp = point%prim(4, m) - pr_inf
      cp = -(cp/temp)
      h(point%flag_2(m)) = h(point%flag_2(m)) + cp*nx*ds
      v(point%flag_2(m)) = v(point%flag_2(m)) + cp*ny*ds
      pitch_mom(point%flag_2(m)) = pitch_mom(point%flag_2(m)) + (-(cp*ny&
&       *ds*(mx-0.25d0))+cp*nx*ds*my)
    END DO
    cl = v*DCOS(theta) - h*DSIN(theta)
    cd = h*DCOS(theta) + v*DSIN(theta)
    clcd = cl/cd
    cm = pitch_mom
  END SUBROUTINE COMPUTE_CL_CD_CM

END MODULE COMPUTE_FORCE_COEFFS_MOD_DIFF

