!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.14 (r7079) -  5 Oct 2018 09:56
!
MODULE PARAMETER_MOD_DIFF
  IMPLICIT NONE
  REAL*8 :: mach
  REAL*8 :: aoa
  REAL*8 :: aoad
  REAL*8 :: theta
  REAL*8 :: thetad
  REAL*8, PARAMETER :: rho_inf=1.0d0
  REAL*8, PARAMETER :: pr_inf=1.0d0/1.4d0
  REAL*8, PARAMETER :: gamma=1.4d0
  REAL*8, PARAMETER :: pi=4.d0*DATAN(1.d0)
  REAL*8, DIMENSION(4) :: q_init, q_inf
  REAL*8, DIMENSION(4) :: q_initd, q_infd

CONTAINS
!  Differentiation of setup_case_parameters in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: q_inf theta q_init
!   with respect to varying inputs: aoa
  SUBROUTINE SETUP_CASE_PARAMETERS_D()
    IMPLICIT NONE
    INTRINSIC DCOS
    INTRINSIC DSIN
!calculate theta
    thetad = pi*aoad/180.d0
    theta = aoa*pi/180.d0
!Setup initial conditions
    q_init(1) = rho_inf
    q_initd = 0.0_8
    q_initd(2) = -(mach*thetad*DSIN(theta))
    q_init(2) = mach*DCOS(theta)
    q_initd(3) = mach*thetad*DCOS(theta)
    q_init(3) = mach*DSIN(theta)
    q_initd(4) = 0.0_8
    q_init(4) = pr_inf
!Setup free stream conditions
    q_inf(1) = rho_inf
    q_infd = 0.0_8
    q_infd(2) = -(mach*thetad*DSIN(theta))
    q_inf(2) = mach*DCOS(theta)
    q_infd(3) = mach*thetad*DCOS(theta)
    q_inf(3) = mach*DSIN(theta)
    q_infd(4) = 0.0_8
    q_inf(4) = pr_inf
  END SUBROUTINE SETUP_CASE_PARAMETERS_D

  SUBROUTINE SETUP_CASE_PARAMETERS()
    IMPLICIT NONE
    INTRINSIC DCOS
    INTRINSIC DSIN
!calculate theta
    theta = aoa*pi/180.d0
!Setup initial conditions
    q_init(1) = rho_inf
    q_init(2) = mach*DCOS(theta)
    q_init(3) = mach*DSIN(theta)
    q_init(4) = pr_inf
!Setup free stream conditions
    q_inf(1) = rho_inf
    q_inf(2) = mach*DCOS(theta)
    q_inf(3) = mach*DSIN(theta)
    q_inf(4) = pr_inf
  END SUBROUTINE SETUP_CASE_PARAMETERS

END MODULE PARAMETER_MOD_DIFF

