!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.14 (r7259) - 18 Jan 2019 09:36
!
MODULE COMPUTE_FORCE_COEFFS_MOD_DIFF
#include <petsc/finclude/petscsys.h>
  USE DATA_STRUCTURE_MOD_DIFF
  USE PETSC_DATA_STRUCTURE_MOD
  IMPLICIT NONE

CONTAINS
!  Differentiation of compute_cl_cd_cm in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: mach theta *clcd *cd *cl *cm
!                *(point.x) *(point.y) *(point.nx) *(point.ny)
!                *(point.prim)
!   with respect to varying inputs: mach theta *clcd *cd *cl *cm
!                *(point.x) *(point.y) *(point.nx) *(point.ny)
!                *(point.prim)
!   Plus diff mem management of: clcd:in cd:in cl:in cm:in point.x:in
!                point.y:in point.nx:in point.ny:in point.prim:in
  SUBROUTINE COMPUTE_CL_CD_CM_B()
    IMPLICIT NONE
    INTEGER :: i, j, k
    INTEGER :: l, m, r
    REAL*8 :: cp, temp
    REAL*8 :: cpb
    REAL*8 :: lx, ly, mx, my, rx, ry
    REAL*8 :: lxb, lyb, mxb, myb, rxb, ryb
    REAL*8 :: ds1, ds2, ds
    REAL*8 :: ds1b, ds2b, dsb
    REAL*8, DIMENSION(shapes) :: h, v, pitch_mom
    REAL*8, DIMENSION(shapes) :: hb, vb
    REAL*8, DIMENSION(shapes) :: lcl, lcd, lcm, lcl1, lcd1
    REAL*8 :: nx, ny
    REAL*8 :: nxb, nyb
    CHARACTER(len=64) :: cp_file
    CHARACTER(len=10) :: itos
    PetscErrorCode :: ierr
    REAL*8 :: tempb
    REAL*8 :: tempb0
    REAL*8 :: tempb1
    REAL*8 :: tempb2
    temp = 0.5d0*rho_inf*mach*mach
    DO j=1,shape_points
      m = shape_points_index(j)
      r = point%right(m)
      l = point%left(m)
      lx = point%x(l)
      ly = point%y(l)
      mx = point%x(m)
      my = point%y(m)
      rx = point%x(r)
      ry = point%y(r)
      ds1 = (mx-lx)**2 + (my-ly)**2
      CALL PUSHREAL8(ds1)
      ds1 = DSQRT(ds1)
      ds2 = (rx-mx)**2 + (ry-my)**2
      CALL PUSHREAL8(ds2)
      ds2 = DSQRT(ds2)
      CALL PUSHREAL8(ds)
      ds = 0.5d0*(ds1+ds2)
      CALL PUSHREAL8(cp)
      cp = point%prim(4, m) - pr_inf
      cp = -(cp/temp)
    END DO
    hb = 0.0_8
    vb = 0.0_8
    vb = DCOS(theta)*clb
    hb = -(DSIN(theta)*clb)
    clb = 0.0_8
    DO j=shape_points,1,-1
      m = shape_points_index(j)
      ny = point%ny(m)
      nyb = ds*cp*vb(point%flag_2(m))
      nx = point%nx(m)
      cpb = ds*nx*hb(point%flag_2(m)) + ds*ny*vb(point%flag_2(m))
      dsb = cp*nx*hb(point%flag_2(m)) + cp*ny*vb(point%flag_2(m))
      nxb = ds*cp*hb(point%flag_2(m))
      cpb = -(cpb/temp)
      CALL POPREAL8(cp)
      pointb%prim(4, m) = pointb%prim(4, m) + cpb
      pointb%ny(m) = pointb%ny(m) + nyb
      pointb%nx(m) = pointb%nx(m) + nxb
      CALL POPREAL8(ds)
      ds1b = 0.5d0*dsb
      ds2b = 0.5d0*dsb
      my = point%y(m)
      r = point%right(m)
      rx = point%x(r)
      ry = point%y(r)
      mx = point%x(m)
      CALL POPREAL8(ds2)
      IF (ds2 .EQ. 0.0) THEN
        ds2b = 0.0
      ELSE
        ds2b = ds2b/(2.D0*DSQRT(ds2))
      END IF
      tempb = 2*(rx-mx)*ds2b
      tempb0 = 2*(ry-my)*ds2b
      rxb = tempb
      ryb = tempb0
      l = point%left(m)
      lx = point%x(l)
      ly = point%y(l)
      CALL POPREAL8(ds1)
      IF (ds1 .EQ. 0.0) THEN
        ds1b = 0.0
      ELSE
        ds1b = ds1b/(2.D0*DSQRT(ds1))
      END IF
      tempb1 = 2*(mx-lx)*ds1b
      mxb = tempb1 - tempb
      tempb2 = 2*(my-ly)*ds1b
      myb = tempb2 - tempb0
      lxb = -tempb1
      lyb = -tempb2
      pointb%y(r) = pointb%y(r) + ryb
      pointb%x(r) = pointb%x(r) + rxb
      pointb%y(m) = pointb%y(m) + myb
      pointb%x(m) = pointb%x(m) + mxb
      pointb%y(l) = pointb%y(l) + lyb
      pointb%x(l) = pointb%x(l) + lxb
    END DO
  END SUBROUTINE COMPUTE_CL_CD_CM_B

  SUBROUTINE COMPUTE_CL_CD_CM()
    IMPLICIT NONE
    INTEGER :: i, j, k
    INTEGER :: l, m, r
    REAL*8 :: cp, temp
    REAL*8 :: lx, ly, mx, my, rx, ry
    REAL*8 :: ds1, ds2, ds
    REAL*8, DIMENSION(shapes) :: h, v, pitch_mom
    REAL*8, DIMENSION(shapes) :: lcl, lcd, lcm, lcl1, lcd1
    REAL*8 :: nx, ny
    CHARACTER(len=64) :: cp_file
    CHARACTER(len=10) :: itos
    PetscErrorCode :: ierr
    cp_file = 'cp/'//'cp-file'
    IF (proc .GT. 1) cp_file = 'cp/'//'cp-file'//TRIM(itos(4, rank))
    OPEN(unit=201, file=trim(cp_file), form='FORMATTED', status=&
&  'REPLACE', action='WRITE') 
    temp = 0.5d0*rho_inf*mach*mach
    h = 0.d0
    v = 0.d0
    pitch_mom = 0.0d0
    DO j=1,shape_points
      m = shape_points_index(j)
      r = point%right(m)
      l = point%left(m)
      lx = point%x(l)
      ly = point%y(l)
      mx = point%x(m)
      my = point%y(m)
      rx = point%x(r)
      ry = point%y(r)
      ds1 = (mx-lx)**2 + (my-ly)**2
      ds1 = DSQRT(ds1)
      ds2 = (rx-mx)**2 + (ry-my)**2
      ds2 = DSQRT(ds2)
      ds = 0.5d0*(ds1+ds2)
      nx = point%nx(m)
      ny = point%ny(m)
      cp = point%prim(4, m) - pr_inf
      cp = -(cp/temp)
      WRITE(201, *) point%flag_2(m), point%x(m), cp
      h(point%flag_2(m)) = h(point%flag_2(m)) + cp*nx*ds
      v(point%flag_2(m)) = v(point%flag_2(m)) + cp*ny*ds
      pitch_mom(point%flag_2(m)) = pitch_mom(point%flag_2(m)) + (-(cp*ny&
&       *ds*(mx-0.25d0))+cp*nx*ds*my)
    END DO
    cl = v*DCOS(theta) - h*DSIN(theta)
    cd = h*DCOS(theta) + v*DSIN(theta)
    cm = pitch_mom
! call MPI_Allreduce(lCl, lCl1 , shapes, MPI_DOUBLE, MPI_SUM, &
! & PETSC_COMM_WORLD, ierr)
! call MPI_Allreduce(lCd, lCd1 , shapes, MPI_DOUBLE, MPI_SUM, &
! & PETSC_COMM_WORLD, ierr)
! call MPI_Allreduce(lCm, Cm , shapes, MPI_DOUBLE, MPI_SUM, &
! & PETSC_COMM_WORLD, ierr)
! Cl = lCl
! Cd = lCd
! Cm = lCm
    clcd = cl/cd
! if(rank == 0) then
!     do j = 1, shapes
!         write(*,'(i4,3e30.20)') j, gCl, gCd, gCm
!     end do
! end if
    CLOSE(unit=201) 
  END SUBROUTINE COMPUTE_CL_CD_CM

END MODULE COMPUTE_FORCE_COEFFS_MOD_DIFF
