1 Command: Command-line option -vars is deprecated: please use -head instead
2 Command: Command-line option -outvars is deprecated: please use -head instead
3 Command: Procedure q_lskum understood as q_lskum_mod.q_lskum
4 q_lskum_mod: (DD15) Module initial_conditions_mod is not defined
5 q_lskum_mod: (DD15) Module ieee_arithmetic is not defined
6 q_lskum: (TC33) External procedure ieee_is_nan is not declared
7 q_lskum: Command: point is not of a differentiable type in procedure q_lskum
8 q_lskum: (AD03) Varied variable residue written by I-O to file 301
9 q_lskum: (AD03) Varied variable dtg written by I-O to file 301
10 q_lskum: (AD03) Varied variable t written by I-O to file 301
11 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%delta
12 q_lskum: (AD12) User help requested: unknown dimension 3 of array *point%temp
13 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%temp
14 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%temp
15 q_lskum: (AD12) User help requested: unknown dimension 3 of array *point%qm
16 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%qm
17 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%qm
18 q_lskum: (AD12) User help requested: unknown dimension 3 of array *point%dq
19 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%dq
20 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%dq
21 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%q
22 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%q
23 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%flux_res
24 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%flux_res
25 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%prim_old
26 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%prim_old
27 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%prim
28 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%prim
29 q_lskum: (AD12) User help requested: unknown dimension 1 of array *cl
30 q_lskum: (AD12) User help requested: unknown dimension 1 of array *cd
31 (DF05) External routine ieee_is_nan, called by (q_lskum), is assumed default In:.1. and Out:.11
32 fpi_solver_mod: (DD15) Module post_processing_mod is not defined
33 fpi_solver: (TC33) External procedure print_primal_output is not declared
34 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%q
35 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%q
36 fpi_solver: (AD12) User help requested: unknown dimension 3 of array *point%qm
37 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%qm
38 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%qm
39 fpi_solver: (AD12) User help requested: unknown dimension 3 of array *point%dq
40 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%dq
41 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%dq
42 fpi_solver: (AD12) User help requested: unknown dimension 3 of array *point%dq
43 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%dq
44 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%dq
45 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%flux_res
46 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%flux_res
47 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%prim
48 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%prim
49 (DF05) External routine print_primal_output, called by (fpi_solver), is assumed default In:. and Out:.
50 state_update_mod: (DD15) Module petsc_data_structure_mod is not defined
51 cal_flux_residual: (AD12) User help requested: unknown dimension 1 of array *point%flux_res
52 cal_flux_residual: (AD12) User help requested: unknown dimension 1 of array *point%flux_res
53 conserved_vector_ubar: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
54 conserved_vector_ubar: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
55 generate_connectivity_mod: (DD15) Module petsc_data_structure_mod is not defined
56 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
57 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
58 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
59 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
60 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
61 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
62 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
63 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
64 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
65 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
66 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
67 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
68 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
69 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
70 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
71 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
72 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
73 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
74 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
75 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
76 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
77 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
78 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
79 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
80 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
81 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
82 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
83 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
84 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
85 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
86 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
87 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
88 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
89 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
90 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
91 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
92 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
93 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
94 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
95 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
96 eval_q_derivatives: (AD12) User help requested: unknown dimension 2 of array *point%qm
97 eval_q_derivatives: (AD12) User help requested: unknown dimension 2 of array *point%qm
98 eval_q_derivatives: (AD12) User help requested: unknown dimension 1 of array temp
99 eval_q_derivatives: (AD12) User help requested: unknown dimension 1 of array temp
100 flux_gxp: (TC33) External procedure derf is not declared
101 flux_gxp: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
102 flux_gxn: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
103 flux_gyp: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
104 flux_gyn: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
105 flux_quad_gxi: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
106 flux_quad_gxi: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
107 flux_quad_gxii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
108 flux_quad_gxii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
109 flux_quad_gxiii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
110 flux_quad_gxiii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
111 flux_quad_gxiv: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
112 flux_quad_gxiv: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
113 (DF05) External routine derf, called by (flux_gxp flux_gxn flux_gyp flux_gyn conserved_vector_ubar flux_quad_gxi flux_quad_gxii flux_quad_gxiii flux_quad_gxiv), is assumed default In:.1. and Out:.11
114 compute_force_coeffs_mod: (DD15) Module petsc_data_structure_mod is not defined
115 compute_cl_cd_cm: (TC20) Variable proc is not declared
116 compute_cl_cd_cm: (TC24) Wrong number of dimensions for array itos: 1 expected, and 2 given
117 compute_cl_cd_cm: (DF03) variable proc is used before initialized
118 compute_cl_cd_cm: (AD03) Varied variable cp written by I-O to file 201
119 compute_cl_cd_cm: (AD03) Varied variable *(point.x)[m] written by I-O to file 201
120 compute_cl_cd_cm: (AD12) User help requested: unknown dimension 1 of array temp
121 compute_entropy_mod: (DD15) Module petsc_data_structure_mod is not defined
122 compute_enstrophy_mod: (DD15) Module petsc_data_structure_mod is not defined
123 stagnation_values_mod: (DD15) Module petsc_data_structure_mod is not defined
124 data_structure_mod: (DD28) Save statement may save extra variables, please use "save::varname" 
125 compute_cl_cd_cm_b: Tool: (TypeSpec tree regeneration) null wrapped type
126 compute_cl_cd_cm: Tool: (TypeSpec tree regeneration) null wrapped type
