!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.14 (r7259) - 18 Jan 2019 09:36
!
MODULE STAGNATION_VALUES_MOD_DIFF
#include <petsc/finclude/petscsys.h>
  USE DATA_STRUCTURE_MOD_DIFF
  USE PETSC_DATA_STRUCTURE_MOD
  IMPLICIT NONE

CONTAINS
  SUBROUTINE STAGNATION_PRESSURE()
    IMPLICIT NONE
    INTEGER :: i, indexmin, indexmax
    REAL*8 :: p0_inf, gammapower, pmin, pmax, p0, mach_t, angle
    REAL*8 :: prim(4)
    INTRINSIC SQRT
    gammapower = gamma/(gamma-1)
    p0_inf = pr_inf*(1+(gamma-1)/2*mach*mach)**gammapower
    DO i=1,max_points
      prim = point%prim(:, i)
      angle = SQRT(gamma*prim(4)/prim(1))
      mach_t = SQRT(prim(2)**2+prim(3)**2)/angle
      p0 = prim(4)*(1+(gamma-1)/2*mach_t*mach_t)**gammapower
      IF (i .EQ. 1) THEN
        pmin = p0
        indexmin = i
        indexmax = i
        pmax = p0
      ELSE IF (p0 .LT. pmin) THEN
        pmin = p0
        indexmin = i
      ELSE IF (p0 .GT. pmax) THEN
        pmax = p0
        indexmax = i
      END IF
    END DO
    WRITE(*, *) 'Stagnation values are ', pmin, ' ', pmax, ' ', pmin/&
&   p0_inf, ' ', pmax/p0_inf, ' ', indexmin, ' ', indexmax
  END SUBROUTINE STAGNATION_PRESSURE

  SUBROUTINE OBJECTIVE_FUNCTION_J()
    IMPLICIT NONE
! if(rank == 0) then
! write(*,*) "J: ", total_loss_stagpressure
! endif
    INTEGER :: i
    REAL*8 :: p0_inf, gammapower, p0, p0_sum, constant, angle, mach_t
    REAL*8 :: prim(4)
    REAL*8 :: total_p0
    INTRINSIC SQRT
    PetscErrorCode :: ierr
    gammapower = gamma/(gamma-1)
    p0_inf = pr_inf*(1+(gamma-1)/2*mach*mach)**gammapower
    constant = 1/(p0_inf**2*plen)
    p0_sum = 0.0d0
    DO i=1,local_points
      prim = point%prim(:, i)
      angle = SQRT(gamma*prim(4)/prim(1))
      mach_t = SQRT(prim(2)**2+prim(3)**2)/angle
      p0 = prim(4)*(1+(gamma-1)/2*mach_t*mach_t)**gammapower
      p0_sum = p0_sum + (p0_inf-p0)**2
    END DO
! total_p0 = p0_sum*1.0
! call MPI_Allreduce(p0_sum, total_p0, 1, MPI_DOUBLE, MPI_SUM, &
!    PETSC_COMM_WORLD, ierr)
    total_loss_stagpressure = p0_sum*constant
  END SUBROUTINE OBJECTIVE_FUNCTION_J

END MODULE STAGNATION_VALUES_MOD_DIFF
