!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.14 (r7259) - 18 Jan 2019 09:36
!
MODULE OBJECTIVE_FUNCTION_MOD_DIFF
  USE DATA_STRUCTURE_MOD_DIFF
  USE COMPUTE_FORCE_COEFFS_MOD_DIFF
  USE COMPUTE_ENTROPY_MOD_DIFF
  IMPLICIT NONE

CONTAINS
!  Differentiation of objective_function in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: *lcl *(point.prim)
!   with respect to varying inputs: *lcl *(point.prim)
!   Plus diff mem management of: lcl:in point.prim:in
  SUBROUTINE OBJECTIVE_FUNCTION_B()
    IMPLICIT NONE
! call compute_entropy()
! call compute_enstrophy()
    CALL COMPUTE_CL_CD_CM_B()
  END SUBROUTINE OBJECTIVE_FUNCTION_B

  SUBROUTINE OBJECTIVE_FUNCTION()
    IMPLICIT NONE
! call compute_entropy()
! call compute_enstrophy()
    CALL COMPUTE_CL_CD_CM()
  END SUBROUTINE OBJECTIVE_FUNCTION

END MODULE OBJECTIVE_FUNCTION_MOD_DIFF
