1 Command: Command-line option -vars is deprecated: please use -head instead
2 Command: Command-line option -outvars is deprecated: please use -head instead
3 Command: Procedure q_lskum understood as q_lskum_mod.q_lskum
4 q_lskum_mod: (DD15) Module initial_conditions_mod is not defined
5 q_lskum_mod: (DD15) Module ieee_arithmetic is not defined
6 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%delta
7 q_lskum: (AD12) User help requested: unknown dimension 3 of array *point%temp
8 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%temp
9 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%temp
10 q_lskum: (AD12) User help requested: unknown dimension 3 of array *point%qm
11 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%qm
12 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%qm
13 q_lskum: (AD12) User help requested: unknown dimension 3 of array *point%dq
14 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%dq
15 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%dq
16 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%q
17 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%q
18 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%flux_res
19 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%flux_res
20 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%prim_old
21 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%prim_old
22 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%prim
23 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%prim
24 fpi_solver_mod: (DD15) Module post_processing_mod is not defined
25 fpi_solver: (TC33) External procedure print_primal_output is not declared
26 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%q
27 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%q
28 fpi_solver: (AD12) User help requested: unknown dimension 3 of array *point%qm
29 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%qm
30 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%qm
31 fpi_solver: (AD12) User help requested: unknown dimension 3 of array *point%dq
32 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%dq
33 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%dq
34 fpi_solver: (AD12) User help requested: unknown dimension 3 of array *point%dq
35 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%dq
36 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%dq
37 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%flux_res
38 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%flux_res
39 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%prim
40 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%prim
41 (DF05) External routine print_primal_output, called by (fpi_solver), is assumed default In:. and Out:.
42 state_update_mod: (DD15) Module petsc_data_structure_mod is not defined
43 cal_flux_residual: (AD12) User help requested: unknown dimension 1 of array *point%flux_res
44 cal_flux_residual: (AD12) User help requested: unknown dimension 1 of array *point%flux_res
45 conserved_vector_ubar: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
46 conserved_vector_ubar: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
47 generate_connectivity_mod: (DD15) Module petsc_data_structure_mod is not defined
48 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
49 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
50 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
51 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
52 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
53 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
54 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
55 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
56 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
57 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
58 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
59 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
60 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
61 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
62 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
63 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
64 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
65 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
66 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
67 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
68 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
69 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
70 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
71 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
72 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
73 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
74 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
75 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
76 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
77 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
78 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
79 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
80 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
81 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
82 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
83 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
84 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
85 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
86 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
87 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
88 eval_q_derivatives: (AD12) User help requested: unknown dimension 2 of array *point%qm
89 eval_q_derivatives: (AD12) User help requested: unknown dimension 2 of array *point%qm
90 flux_gxp: (TC33) External procedure derf is not declared
91 flux_gxp: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
92 flux_gxn: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
93 flux_gyp: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
94 flux_gyn: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
95 flux_quad_gxi: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
96 flux_quad_gxi: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
97 flux_quad_gxii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
98 flux_quad_gxii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
99 flux_quad_gxiii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
100 flux_quad_gxiii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
101 flux_quad_gxiv: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
102 flux_quad_gxiv: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
103 (DF05) External routine derf, called by (flux_gxp flux_gxn flux_gyp flux_gyn conserved_vector_ubar flux_quad_gxi flux_quad_gxii flux_quad_gxiii flux_quad_gxiv), is assumed default In:.1. and Out:.11
104 compute_force_coeffs_mod: (DD15) Module petsc_data_structure_mod is not defined
105 compute_cl_cd_cm: (TC20) Variable proc is not declared
106 compute_cl_cd_cm: (TC24) Wrong number of dimensions for array itos: 1 expected, and 2 given
107 compute_cl_cd_cm: (DF03) variable proc is used before initialized
108 compute_cl_cd_cm: (AD03) Varied variable cp written by I-O to file 201
109 compute_cl_cd_cm: (AD03) Varied variable *(point.x)[m] written by I-O to file 201
110 compute_entropy_mod: (DD15) Module petsc_data_structure_mod is not defined
111 compute_enstrophy_mod: (DD15) Module petsc_data_structure_mod is not defined
112 stagnation_values_mod: (DD15) Module petsc_data_structure_mod is not defined
113 data_structure_mod: (DD28) Save statement may save extra variables, please use "save::varname" 
114 compute_cl_cd_cm_b: Tool: (TypeSpec tree regeneration) null wrapped type
115 compute_cl_cd_cm: Tool: (TypeSpec tree regeneration) null wrapped type
