1 Command: Command-line option -vars is deprecated: please use -head instead
2 Command: Command-line option -outvars is deprecated: please use -head instead
3 Command: Procedure q_lskum understood as q_lskum_mod.q_lskum
4 q_lskum_mod: (DD15) Module initial_conditions_mod is not defined
5 q_lskum_mod: (DD15) Module ieee_arithmetic is not defined
6 q_lskum: (TC33) External procedure ieee_is_nan is not declared
7 (DF05) External routine ieee_is_nan, called by (q_lskum), is assumed default In:.1. and Out:.11
8 fpi_solver_mod: (DD15) Module post_processing_mod is not defined
9 fpi_solver: (TC33) External procedure print_primal_output is not declared
10 (DF05) External routine print_primal_output, called by (fpi_solver), is assumed default In:. and Out:.
11 state_update_mod: (DD15) Module petsc_data_structure_mod is not defined
12 conserved_vector_ubar: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
13 conserved_vector_ubar: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
14 generate_connectivity_mod: (DD15) Module petsc_data_structure_mod is not defined
15 flux_gxp: (TC33) External procedure derf is not declared
16 flux_gxp: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
17 flux_gxn: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
18 flux_gyp: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
19 flux_gyn: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
20 flux_quad_gxi: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
21 flux_quad_gxi: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
22 flux_quad_gxii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
23 flux_quad_gxii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
24 flux_quad_gxiii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
25 flux_quad_gxiii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
26 flux_quad_gxiv: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
27 flux_quad_gxiv: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
28 (DF05) External routine derf, called by (flux_gxp flux_gxn flux_gyp flux_gyn conserved_vector_ubar flux_quad_gxi flux_quad_gxii flux_quad_gxiii flux_quad_gxiv), is assumed default In:.1. and Out:.11
29 compute_force_coeffs_mod: (DD15) Module petsc_data_structure_mod is not defined
30 compute_cl_cd_cm: (TC20) Variable proc is not declared
31 compute_cl_cd_cm: (TC24) Wrong number of dimensions for array itos: 1 expected, and 2 given
32 compute_cl_cd_cm: (DF03) variable proc is used before initialized
33 compute_cl_cd_cm: (AD03) Varied variable cp written by I-O to file 201
34 compute_cl_cd_cm: (AD03) Varied variable *(point.x)[m] written by I-O to file 201
35 compute_entropy_mod: (DD15) Module petsc_data_structure_mod is not defined
36 compute_enstrophy_mod: (DD15) Module petsc_data_structure_mod is not defined
37 stagnation_values_mod: (DD15) Module petsc_data_structure_mod is not defined
38 data_structure_mod: (DD28) Save statement may save extra variables, please use "save::varname" 
39 objective_function_j: (DF03) variable total_p0 is used before initialized
40 compute_cl_cd_cm_d: Tool: (TypeSpec tree regeneration) null wrapped type
41 compute_cl_cd_cm: Tool: (TypeSpec tree regeneration) null wrapped type
