!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
MODULE Q_LSKUM_MOD_DIFF
!	First written on 14.10.2016
!	updated on Dec 26, 2016
!	updated on Dec 29, 2016
  USE DATA_STRUCTURE_MOD_DIFF
  USE POINT_NORMALS_MOD_DIFF
  USE GENERATE_CONNECTIVITY_MOD_DIFF
  USE FPI_SOLVER_MOD_DIFF
  USE INITIAL_CONDITIONS_MOD
  USE IEEE_ARITHMETIC
  IMPLICIT NONE

CONTAINS
!  Differentiation of q_lskum in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: *vector_cost_func
!   with respect to varying inputs: *(point.x) *(point.y)
!   RW status of diff variables: *cd:(loc) *vector_cost_func:in-killed
!                *(point.x):out *(point.y):out *(point.nx):(loc)
!                *(point.ny):(loc) *(point.prim):(loc) *(point.prim_old):(loc)
!                *(point.flux_res):(loc) *(point.q):(loc) *(point.dq):(loc)
!                *(point.qm):(loc) *(point.temp):(loc) *(point.delta):(loc)
!   Plus diff mem management of: cd:in vector_cost_func:in point.x:in
!                point.y:in point.nx:in point.ny:in point.prim:in
!                point.prim_old:in point.flux_res:in point.q:in
!                point.dq:in point.qm:in point.temp:in point.delta:in
  SUBROUTINE Q_LSKUM_B()
    USE DIFFSIZES
!  Hint: ISIZE1OFDrfpoint_delta should be the size of dimension 1 of array *point%delta
!  Hint: ISIZE3OFDrfpoint_temp should be the size of dimension 3 of array *point%temp
!  Hint: ISIZE2OFDrfpoint_temp should be the size of dimension 2 of array *point%temp
!  Hint: ISIZE1OFDrfpoint_temp should be the size of dimension 1 of array *point%temp
!  Hint: ISIZE3OFDrfpoint_qm should be the size of dimension 3 of array *point%qm
!  Hint: ISIZE2OFDrfpoint_qm should be the size of dimension 2 of array *point%qm
!  Hint: ISIZE1OFDrfpoint_qm should be the size of dimension 1 of array *point%qm
!  Hint: ISIZE3OFDrfpoint_dq should be the size of dimension 3 of array *point%dq
!  Hint: ISIZE2OFDrfpoint_dq should be the size of dimension 2 of array *point%dq
!  Hint: ISIZE1OFDrfpoint_dq should be the size of dimension 1 of array *point%dq
!  Hint: ISIZE2OFDrfpoint_q should be the size of dimension 2 of array *point%q
!  Hint: ISIZE1OFDrfpoint_q should be the size of dimension 1 of array *point%q
!  Hint: ISIZE2OFDrfpoint_flux_res should be the size of dimension 2 of array *point%flux_res
!  Hint: ISIZE1OFDrfpoint_flux_res should be the size of dimension 1 of array *point%flux_res
!  Hint: ISIZE2OFDrfpoint_prim_old should be the size of dimension 2 of array *point%prim_old
!  Hint: ISIZE1OFDrfpoint_prim_old should be the size of dimension 1 of array *point%prim_old
!  Hint: ISIZE2OFDrfpoint_prim should be the size of dimension 2 of array *point%prim
!  Hint: ISIZE1OFDrfpoint_prim should be the size of dimension 1 of array *point%prim
    IMPLICIT NONE
    INTEGER :: i
    IF (rank .EQ. 0) OPEN(unit=301, file='residue', form='FORMATTED', &
&                   status='REPLACE', action='WRITE') 
    CALL COMPUTE_NORMALS()
    CALL GENERATE_CONNECTIVITY()
    IF (rank .EQ. 0) THEN
      WRITE(*, *) 
      WRITE(*, *) '%%%%-Normals and connectivity generated-%%%'
      WRITE(*, *) 
    END IF
    IF (rank .EQ. 0) THEN
      WRITE(*, *) '%%%%%%%%%%%%%-Iterations begin-%%%%%%%%%%%%'
      WRITE(*, *) 
    END IF
    IF (restart .EQ. 0) itr = 0
    DO it=itr+1,itr+max_iters
      CALL PUSHREAL8ARRAY(point%delta, ISIZE1OFDrfpoint_delta)
      CALL PUSHREAL8ARRAY(point%temp, ISIZE1OFDrfpoint_temp*&
&                   ISIZE2OFDrfpoint_temp*ISIZE3OFDrfpoint_temp)
      CALL PUSHREAL8ARRAY(point%qm, ISIZE1OFDrfpoint_qm*&
&                   ISIZE2OFDrfpoint_qm*ISIZE3OFDrfpoint_qm)
      CALL PUSHREAL8ARRAY(point%dq, ISIZE1OFDrfpoint_dq*&
&                   ISIZE2OFDrfpoint_dq*ISIZE3OFDrfpoint_dq)
      CALL PUSHREAL8ARRAY(point%q, ISIZE1OFDrfpoint_q*ISIZE2OFDrfpoint_q&
&                  )
      CALL PUSHREAL8ARRAY(point%flux_res, ISIZE1OFDrfpoint_flux_res*&
&                   ISIZE2OFDrfpoint_flux_res)
      CALL PUSHREAL8ARRAY(point%prim_old, ISIZE1OFDrfpoint_prim_old*&
&                   ISIZE2OFDrfpoint_prim_old)
      CALL PUSHREAL8ARRAY(point%prim, ISIZE1OFDrfpoint_prim*&
&                   ISIZE2OFDrfpoint_prim)
      CALL FPI_SOLVER(it)
! if (rank==0) then
      WRITE(*, '(a12,i8,a15,e30.20)') 'iterations:', it, 'residue:', &
&     residue
      WRITE(301, *) it, residue
    END DO
! end if
    CLOSE(unit=301) 
    IF (ALLOCATED(cdb)) cdb = 0.0_8
    pointb%x = 0.0_8
    pointb%y = 0.0_8
    pointb%nx = 0.0_8
    pointb%ny = 0.0_8
    pointb%prim = 0.0_8
    pointb%prim_old = 0.0_8
    pointb%flux_res = 0.0_8
    pointb%q = 0.0_8
    pointb%dq = 0.0_8
    pointb%qm = 0.0_8
    pointb%temp = 0.0_8
    pointb%delta = 0.0_8
    DO it=itr+max_iters,itr+1,-1
      CALL POPREAL8ARRAY(point%prim, ISIZE1OFDrfpoint_prim*&
&                  ISIZE2OFDrfpoint_prim)
      CALL POPREAL8ARRAY(point%prim_old, ISIZE1OFDrfpoint_prim_old*&
&                  ISIZE2OFDrfpoint_prim_old)
      CALL POPREAL8ARRAY(point%flux_res, ISIZE1OFDrfpoint_flux_res*&
&                  ISIZE2OFDrfpoint_flux_res)
      CALL POPREAL8ARRAY(point%q, ISIZE1OFDrfpoint_q*ISIZE2OFDrfpoint_q)
      CALL POPREAL8ARRAY(point%dq, ISIZE1OFDrfpoint_dq*&
&                  ISIZE2OFDrfpoint_dq*ISIZE3OFDrfpoint_dq)
      CALL POPREAL8ARRAY(point%qm, ISIZE1OFDrfpoint_qm*&
&                  ISIZE2OFDrfpoint_qm*ISIZE3OFDrfpoint_qm)
      CALL POPREAL8ARRAY(point%temp, ISIZE1OFDrfpoint_temp*&
&                  ISIZE2OFDrfpoint_temp*ISIZE3OFDrfpoint_temp)
      CALL POPREAL8ARRAY(point%delta, ISIZE1OFDrfpoint_delta)
      CALL FPI_SOLVER_B(it)
    END DO
    CALL COMPUTE_NORMALS_B()
  END SUBROUTINE Q_LSKUM_B

  SUBROUTINE Q_LSKUM()
    IMPLICIT NONE
    INTEGER :: i
    IF (rank .EQ. 0) OPEN(unit=301, file='residue', form='FORMATTED', &
&                   status='REPLACE', action='WRITE') 
    CALL COMPUTE_NORMALS()
    CALL GENERATE_CONNECTIVITY()
    IF (rank .EQ. 0) THEN
      WRITE(*, *) 
      WRITE(*, *) '%%%%-Normals and connectivity generated-%%%'
      WRITE(*, *) 
    END IF
! Set U_old to U for first iteration
    DO i=1,local_points
      point%u_old(1, i) = point%prim(1, i)
      point%u_old(2, i) = point%prim(1, i)*point%prim(2, i)
      point%u_old(3, i) = point%prim(1, i)*point%prim(3, i)
      point%u_old(4, i) = 2.5d0*point%prim(4, i) + 0.5d0*point%prim(1, i&
&       )*(point%prim(2, i)*point%prim(2, i)+point%prim(3, i)*point%prim&
&       (3, i))
    END DO
    IF (rank .EQ. 0) THEN
      WRITE(*, *) '%%%%%%%%%%%%%-Iterations begin-%%%%%%%%%%%%'
      WRITE(*, *) 
    END IF
    IF (restart .EQ. 0) itr = 0
    DO it=itr+1,itr+max_iters
      CALL FPI_SOLVER(it)
! if (rank==0) then
      WRITE(*, '(a12,i8,a15,e30.20)') 'iterations:', it, 'residue:', &
&     residue
      WRITE(301, *) it, residue
    END DO
! end if
    CLOSE(unit=301) 
  END SUBROUTINE Q_LSKUM

END MODULE Q_LSKUM_MOD_DIFF

