1 Command: Command-line option -vars is deprecated: please use -head instead
2 Command: Command-line option -outvars is deprecated: please use -head instead
3 Command: Procedure q_lskum understood as q_lskum_mod.q_lskum
4 q_lskum_mod: (DD15) Module initial_conditions_mod is not defined
5 q_lskum_mod: (DD15) Module ieee_arithmetic is not defined
6 q_lskum: (TC33) External procedure ieee_is_nan is not declared
7 q_lskum: Command: point is not of a differentiable type in procedure q_lskum
8 q_lskum: (AD03) Varied variable residue written by I-O to file 301
9 q_lskum: (AD03) Varied variable dtg written by I-O to file 301
10 q_lskum: (AD03) Varied variable t written by I-O to file 301
11 (DF05) External routine ieee_is_nan, called by (q_lskum), is assumed default In:.1. and Out:.11
12 fpi_solver_mod: (DD15) Module post_processing_mod is not defined
13 fpi_solver: (TC33) External procedure print_primal_output is not declared
14 (DF05) External routine print_primal_output, called by (fpi_solver), is assumed default In:. and Out:.
15 state_update_mod: (DD15) Module petsc_data_structure_mod is not defined
16 conserved_vector_ubar: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
17 conserved_vector_ubar: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
18 generate_connectivity_mod: (DD15) Module petsc_data_structure_mod is not defined
19 flux_gxp: (TC33) External procedure derf is not declared
20 flux_gxp: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
21 flux_gxn: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
22 flux_gyp: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
23 flux_gyn: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
24 flux_quad_gxi: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
25 flux_quad_gxi: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
26 flux_quad_gxii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
27 flux_quad_gxii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
28 flux_quad_gxiii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
29 flux_quad_gxiii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
30 flux_quad_gxiv: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
31 flux_quad_gxiv: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
32 (DF05) External routine derf, called by (flux_gxp flux_gxn flux_gyp flux_gyn conserved_vector_ubar flux_quad_gxi flux_quad_gxii flux_quad_gxiii flux_quad_gxiv), is assumed default In:.1. and Out:.11
33 compute_force_coeffs_mod: (DD15) Module petsc_data_structure_mod is not defined
34 compute_cl_cd_cm: (TC20) Variable proc is not declared
35 compute_cl_cd_cm: (TC24) Wrong number of dimensions for array itos: 1 expected, and 2 given
36 compute_cl_cd_cm: (DF03) variable proc is used before initialized
37 compute_cl_cd_cm: (AD03) Varied variable cp written by I-O to file 201
38 compute_cl_cd_cm: (AD03) Varied variable *(point.x)[m] written by I-O to file 201
39 compute_entropy_mod: (DD15) Module petsc_data_structure_mod is not defined
40 compute_enstrophy_mod: (DD15) Module petsc_data_structure_mod is not defined
41 stagnation_values_mod: (DD15) Module petsc_data_structure_mod is not defined
42 data_structure_mod: (DD28) Save statement may save extra variables, please use "save::varname" 
43 compute_cl_cd_cm_d: Tool: (TypeSpec tree regeneration) null wrapped type
44 compute_cl_cd_cm: Tool: (TypeSpec tree regeneration) null wrapped type
