!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.14 (r7259) - 18 Jan 2019 09:36
!
MODULE Q_VARIABLES_MOD_DIFF
  USE DATA_STRUCTURE_MOD_DIFF
  IMPLICIT NONE

CONTAINS
!  Differentiation of eval_q_variables in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: *(point.prim) *(point.q)
!   with respect to varying inputs: *(point.prim) *(point.q)
!   Plus diff mem management of: point.prim:in point.q:in
  SUBROUTINE EVAL_Q_VARIABLES_B()
    IMPLICIT NONE
    INTEGER :: k
    REAL*8 :: rho, u1, u2, pr, beta
    REAL*8 :: rhob, u1b, u2b, prb, betab
    REAL*8 :: two_times_beta
    REAL*8 :: two_times_betab
    INTRINSIC DLOG
    REAL*8 :: tempb
    DO k=max_points,1,-1
      two_times_betab = -pointb%q(4, k)
      pointb%q(4, k) = 0.0_8
      pr = point%prim(4, k)
      rho = point%prim(1, k)
      beta = 0.5d0*rho/pr
      two_times_beta = 2.0d0*beta
      u2 = point%prim(3, k)
      two_times_betab = two_times_betab + u2*pointb%q(3, k)
      u2b = two_times_beta*pointb%q(3, k)
      pointb%q(3, k) = 0.0_8
      u1 = point%prim(2, k)
      two_times_betab = two_times_betab + u1*pointb%q(2, k)
      u1b = two_times_beta*pointb%q(2, k)
      pointb%q(2, k) = 0.0_8
      betab = (2.5d0/beta-u2**2-u1**2)*pointb%q(1, k) + 2.0d0*&
&       two_times_betab
      u1b = u1b - beta*2*u1*pointb%q(1, k)
      u2b = u2b - beta*2*u2*pointb%q(1, k)
      tempb = 0.5d0*betab/pr
      rhob = tempb + pointb%q(1, k)/rho
      pointb%q(1, k) = 0.0_8
      prb = -(rho*tempb/pr)
      pointb%prim(4, k) = pointb%prim(4, k) + prb
      pointb%prim(3, k) = pointb%prim(3, k) + u2b
      pointb%prim(2, k) = pointb%prim(2, k) + u1b
      pointb%prim(1, k) = pointb%prim(1, k) + rhob
    END DO
  END SUBROUTINE EVAL_Q_VARIABLES_B

  SUBROUTINE EVAL_Q_VARIABLES()
    IMPLICIT NONE
    INTEGER :: k
    REAL*8 :: rho, u1, u2, pr, beta
    REAL*8 :: two_times_beta
    INTRINSIC DLOG
!
    DO k=1,max_points
      rho = point%prim(1, k)
      u1 = point%prim(2, k)
      u2 = point%prim(3, k)
      pr = point%prim(4, k)
      beta = 0.5d0*rho/pr
      point%q(1, k) = DLOG(rho) + DLOG(beta)*2.5d0 - beta*(u1*u1+u2*u2)
      two_times_beta = 2.0d0*beta
      point%q(2, k) = two_times_beta*u1
      point%q(3, k) = two_times_beta*u2
      point%q(4, k) = -two_times_beta
    END DO
  END SUBROUTINE EVAL_Q_VARIABLES

!  Differentiation of eval_q_derivatives in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: *(point.q) *(point.dq)
!   with respect to varying inputs: *(point.q) *(point.dq)
!   Plus diff mem management of: point.q:in point.dq:in
  SUBROUTINE EVAL_Q_DERIVATIVES_B()
    IMPLICIT NONE
    INTEGER :: i, k, r, nbh
    REAL*8 :: x_i, y_i, x_k, y_k
    REAL*8 :: delx, dely, dist, weights
    REAL*8 :: sum_delx_sqr, sum_dely_sqr, sum_delx_dely
    REAL*8 :: sum_delx_delq(4), sum_dely_delq(4)
    REAL*8 :: sum_delx_delqb(4), sum_dely_delqb(4)
    REAL*8 :: det, delq, temp
    REAL*8 :: one_by_det
    INTRINSIC DSQRT
    REAL*8, DIMENSION(4) :: tempb
    REAL*8, DIMENSION(4) :: tempb0
    INTEGER :: ad_to
    DO i=1,max_points
      x_i = point%x(i)
      y_i = point%y(i)
      CALL PUSHREAL8(sum_delx_sqr)
      sum_delx_sqr = 0.d0
      CALL PUSHREAL8(sum_dely_sqr)
      sum_dely_sqr = 0.d0
      CALL PUSHREAL8(sum_delx_dely)
      sum_delx_dely = 0.d0
      DO k=1,point%nbhs(i)
        nbh = point%conn(i, k)
        x_k = point%x(nbh)
        y_k = point%y(nbh)
        delx = x_k - x_i
        dely = y_k - y_i
        dist = DSQRT(delx*delx + dely*dely)
        CALL PUSHREAL8(weights)
        weights = dist**power
        sum_delx_sqr = sum_delx_sqr + delx*delx*weights
        sum_dely_sqr = sum_dely_sqr + dely*dely*weights
        sum_delx_dely = sum_delx_dely + delx*dely*weights
      END DO
      CALL PUSHINTEGER4(k - 1)
      det = sum_delx_sqr*sum_dely_sqr - sum_delx_dely*sum_delx_dely
      CALL PUSHREAL8(one_by_det)
      one_by_det = 1.0d0/det
    END DO
    DO i=max_points,1,-1
      sum_delx_delqb = 0.0_8
      sum_dely_delqb = 0.0_8
      sum_dely_delqb = one_by_det*sum_delx_sqr*pointb%dq(2, :, i)
      sum_delx_delqb = -(one_by_det*sum_delx_dely*pointb%dq(2, :, i))
      pointb%dq(2, :, i) = 0.0_8
      sum_delx_delqb = sum_delx_delqb + one_by_det*sum_dely_sqr*pointb%&
&       dq(1, :, i)
      sum_dely_delqb = sum_dely_delqb - one_by_det*sum_delx_dely*pointb%&
&       dq(1, :, i)
      pointb%dq(1, :, i) = 0.0_8
      CALL POPREAL8(one_by_det)
      y_i = point%y(i)
      x_i = point%x(i)
      CALL POPINTEGER4(ad_to)
      DO k=ad_to,1,-1
        nbh = point%conn(i, k)
        y_k = point%y(nbh)
        dely = y_k - y_i
        tempb = weights*dely*sum_dely_delqb
        pointb%q(:, nbh) = pointb%q(:, nbh) + tempb
        pointb%q(:, i) = pointb%q(:, i) - tempb
        x_k = point%x(nbh)
        delx = x_k - x_i
        tempb0 = weights*delx*sum_delx_delqb
        pointb%q(:, nbh) = pointb%q(:, nbh) + tempb0
        pointb%q(:, i) = pointb%q(:, i) - tempb0
        CALL POPREAL8(weights)
      END DO
      CALL POPREAL8(sum_delx_dely)
      CALL POPREAL8(sum_dely_sqr)
      CALL POPREAL8(sum_delx_sqr)
    END DO
  END SUBROUTINE EVAL_Q_DERIVATIVES_B

  SUBROUTINE EVAL_Q_DERIVATIVES()
    IMPLICIT NONE
    INTEGER :: i, k, r, nbh
    REAL*8 :: x_i, y_i, x_k, y_k
    REAL*8 :: delx, dely, dist, weights
    REAL*8 :: sum_delx_sqr, sum_dely_sqr, sum_delx_dely
    REAL*8 :: sum_delx_delq(4), sum_dely_delq(4)
    REAL*8 :: det, delq, temp
    REAL*8 :: one_by_det
    ! INTRINSIC DSQRT
    DO i=1,max_points
      x_i = point%x(i)
      y_i = point%y(i)
      sum_delx_sqr = 0.d0
      sum_dely_sqr = 0.d0
      sum_delx_dely = 0.d0
      sum_delx_delq = 0.d0
      sum_dely_delq = 0.d0
      point%qm(1, :, i) = point%q(:, i)
      point%qm(2, :, i) = point%q(:, i)
      DO k=1,point%nbhs(i)
        nbh = point%conn(i, k)
        DO r=1,4
          IF (point%q(r, nbh) .GT. point%qm(1, r, i)) point%qm(1, r, i)&
&            = point%q(r, nbh)
          IF (point%q(r, nbh) .LT. point%qm(2, r, i)) point%qm(2, r, i)&
&            = point%q(r, nbh)
        END DO
        x_k = point%x(nbh)
        y_k = point%y(nbh)
        delx = x_k - x_i
        dely = y_k - y_i
        dist = DSQRT(delx*delx + dely*dely)
        weights = dist**power
        sum_delx_sqr = sum_delx_sqr + delx*delx*weights
        sum_dely_sqr = sum_dely_sqr + dely*dely*weights
        sum_delx_dely = sum_delx_dely + delx*dely*weights
        sum_delx_delq = sum_delx_delq + weights*delx*(point%q(:, nbh)-&
&         point%q(:, i))
        sum_dely_delq = sum_dely_delq + weights*dely*(point%q(:, nbh)-&
&         point%q(:, i))
      END DO
      det = sum_delx_sqr*sum_dely_sqr - sum_delx_dely*sum_delx_dely
      one_by_det = 1.0d0/det
      point%dq(1, :, i) = (sum_delx_delq*sum_dely_sqr-sum_dely_delq*&
&       sum_delx_dely)*one_by_det
      point%dq(2, :, i) = (sum_dely_delq*sum_delx_sqr-sum_delx_delq*&
&       sum_delx_dely)*one_by_det
    END DO
  END SUBROUTINE EVAL_Q_DERIVATIVES

!  Differentiation of eval_q_double_derivatives in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: *(point.dq) *(point.ddq)
!   with respect to varying inputs: *(point.dq) *(point.ddq)
!   Plus diff mem management of: point.dq:in point.ddq:in
  SUBROUTINE EVAL_Q_DOUBLE_DERIVATIVES_B()
    IMPLICIT NONE
! local variables
    INTEGER :: i
    INTEGER :: k, r, nbh
    REAL*8 :: x_i, y_i, x_k, y_k
    REAL*8 :: delx, dely, dist, weights
    REAL*8 :: sum_delx_sqr, sum_dely_sqr, sum_delx_dely
    REAL*8 :: sum_delx_del_qx(4), sum_delx_del_qy(4), sum_dely_del_qx(4)&
&   , sum_dely_del_qy(4)
    REAL*8 :: sum_delx_del_qxb(4), sum_delx_del_qyb(4), sum_dely_del_qxb&
&   (4), sum_dely_del_qyb(4)
    REAL*8 :: det, delq, temp
    REAL*8 :: one_by_det
    INTRINSIC DSQRT
    REAL*8, DIMENSION(4) :: tempb
    REAL*8, DIMENSION(4) :: tempb0
    REAL*8, DIMENSION(4) :: tempb1
    REAL*8, DIMENSION(4) :: tempb2
    INTEGER :: ad_to
    DO i=1,max_points
      x_i = point%x(i)
      y_i = point%y(i)
      CALL PUSHREAL8(sum_delx_sqr)
      sum_delx_sqr = 0.d0
      CALL PUSHREAL8(sum_dely_sqr)
      sum_dely_sqr = 0.d0
      CALL PUSHREAL8(sum_delx_dely)
      sum_delx_dely = 0.d0
      DO k=1,point%nbhs(i)
        nbh = point%conn(i, k)
        x_k = point%x(nbh)
        y_k = point%y(nbh)
        delx = x_k - x_i
        dely = y_k - y_i
        dist = DSQRT(delx*delx + dely*dely)
        CALL PUSHREAL8(weights)
        weights = dist**power
        sum_delx_sqr = sum_delx_sqr + delx*delx*weights
        sum_dely_sqr = sum_dely_sqr + dely*dely*weights
        sum_delx_dely = sum_delx_dely + delx*dely*weights
      END DO
      CALL PUSHINTEGER4(k - 1)
      det = sum_delx_sqr*sum_dely_sqr - sum_delx_dely*sum_delx_dely
      CALL PUSHREAL8(one_by_det)
      one_by_det = 1.0d0/det
    END DO
    DO i=max_points,1,-1
      sum_delx_del_qyb = 0.0_8
      sum_dely_del_qyb = 0.0_8
      sum_dely_del_qyb = one_by_det*sum_delx_sqr*pointb%ddq(3, :, i)
      sum_delx_del_qyb = -(one_by_det*sum_delx_dely*pointb%ddq(3, :, i))
      pointb%ddq(3, :, i) = 0.0_8
      sum_delx_del_qyb = sum_delx_del_qyb + one_by_det*sum_dely_sqr*&
&       pointb%ddq(2, :, i)
      sum_dely_del_qyb = sum_dely_del_qyb - one_by_det*sum_delx_dely*&
&       pointb%ddq(2, :, i)
      pointb%ddq(2, :, i) = 0.0_8
      sum_delx_del_qxb = 0.0_8
      sum_dely_del_qxb = 0.0_8
      sum_delx_del_qxb = one_by_det*sum_dely_sqr*pointb%ddq(1, :, i)
      sum_dely_del_qxb = -(one_by_det*sum_delx_dely*pointb%ddq(1, :, i))
      pointb%ddq(1, :, i) = 0.0_8
      CALL POPREAL8(one_by_det)
      y_i = point%y(i)
      x_i = point%x(i)
      CALL POPINTEGER4(ad_to)
      DO k=ad_to,1,-1
        nbh = point%conn(i, k)
        y_k = point%y(nbh)
        dely = y_k - y_i
        tempb = weights*dely*sum_dely_del_qyb
        pointb%dq(2, :, nbh) = pointb%dq(2, :, nbh) + tempb
        pointb%dq(2, :, i) = pointb%dq(2, :, i) - tempb
        tempb0 = weights*dely*sum_dely_del_qxb
        pointb%dq(1, :, nbh) = pointb%dq(1, :, nbh) + tempb0
        pointb%dq(1, :, i) = pointb%dq(1, :, i) - tempb0
        x_k = point%x(nbh)
        delx = x_k - x_i
        tempb1 = weights*delx*sum_delx_del_qyb
        pointb%dq(2, :, nbh) = pointb%dq(2, :, nbh) + tempb1
        pointb%dq(2, :, i) = pointb%dq(2, :, i) - tempb1
        tempb2 = weights*delx*sum_delx_del_qxb
        pointb%dq(1, :, nbh) = pointb%dq(1, :, nbh) + tempb2
        pointb%dq(1, :, i) = pointb%dq(1, :, i) - tempb2
        CALL POPREAL8(weights)
      END DO
      CALL POPREAL8(sum_delx_dely)
      CALL POPREAL8(sum_dely_sqr)
      CALL POPREAL8(sum_delx_sqr)
    END DO
  END SUBROUTINE EVAL_Q_DOUBLE_DERIVATIVES_B

  SUBROUTINE EVAL_Q_DOUBLE_DERIVATIVES()
    IMPLICIT NONE
! local variables
    INTEGER :: i
    INTEGER :: k, r, nbh
    REAL*8 :: x_i, y_i, x_k, y_k
    REAL*8 :: delx, dely, dist, weights
    REAL*8 :: sum_delx_sqr, sum_dely_sqr, sum_delx_dely
    REAL*8 :: sum_delx_del_qx(4), sum_delx_del_qy(4), sum_dely_del_qx(4)&
&   , sum_dely_del_qy(4)
    REAL*8 :: det, delq, temp
    REAL*8 :: one_by_det
    ! INTRINSIC DSQRT
    DO i=1,max_points
      x_i = point%x(i)
      y_i = point%y(i)
      sum_delx_sqr = 0.d0
      sum_dely_sqr = 0.d0
      sum_delx_dely = 0.d0
      sum_delx_del_qx = 0.d0
      sum_delx_del_qy = 0.d0
      sum_dely_del_qx = 0.d0
      sum_dely_del_qy = 0.d0
      DO k=1,point%nbhs(i)
        nbh = point%conn(i, k)
        x_k = point%x(nbh)
        y_k = point%y(nbh)
        delx = x_k - x_i
        dely = y_k - y_i
        dist = DSQRT(delx*delx + dely*dely)
        weights = dist**power
        sum_delx_sqr = sum_delx_sqr + delx*delx*weights
        sum_dely_sqr = sum_dely_sqr + dely*dely*weights
        sum_delx_dely = sum_delx_dely + delx*dely*weights
        sum_delx_del_qx = sum_delx_del_qx + weights*delx*(point%dq(1, :&
&         , nbh)-point%dq(1, :, i))
        sum_delx_del_qy = sum_delx_del_qy + weights*delx*(point%dq(2, :&
&         , nbh)-point%dq(2, :, i))
        sum_dely_del_qx = sum_dely_del_qx + weights*dely*(point%dq(1, :&
&         , nbh)-point%dq(1, :, i))
        sum_dely_del_qy = sum_dely_del_qy + weights*dely*(point%dq(2, :&
&         , nbh)-point%dq(2, :, i))
      END DO
      det = sum_delx_sqr*sum_dely_sqr - sum_delx_dely*sum_delx_dely
      one_by_det = 1.0d0/det
      point%ddq(1, :, i) = (sum_delx_del_qx*sum_dely_sqr-sum_dely_del_qx&
&       *sum_delx_dely)*one_by_det
      point%ddq(2, :, i) = (sum_delx_del_qy*sum_dely_sqr-sum_dely_del_qy&
&       *sum_delx_dely)*one_by_det
      point%ddq(3, :, i) = (sum_dely_del_qy*sum_delx_sqr-sum_delx_del_qy&
&       *sum_delx_dely)*one_by_det
    END DO
  END SUBROUTINE EVAL_Q_DOUBLE_DERIVATIVES

!  Differentiation of eval_q_inner_loop in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: *(point.q) *(point.dq) *(point.ddq)
!                *(point.temp)
!   with respect to varying inputs: *(point.q) *(point.dq) *(point.ddq)
!                *(point.temp)
!   Plus diff mem management of: point.q:in point.dq:in point.ddq:in
!                point.temp:in
  SUBROUTINE EVAL_Q_INNER_LOOP_B()
    IMPLICIT NONE
    INTEGER :: i
    INTEGER :: k, r, nbh
    REAL*8 :: x_i, y_i, x_k, y_k
    REAL*8 :: delx, dely, dist, weights
    REAL*8 :: sum_delx_sqr, sum_dely_sqr, sum_delx_dely
    REAL*8 :: det, temp
    REAL*8 :: one_by_det
    REAL*8 :: sum_delx_delq1, sum_delx_delq2, sum_delx_delq3, &
&   sum_delx_delq4
    REAL*8 :: sum_delx_delq1b, sum_delx_delq2b, sum_delx_delq3b, &
&   sum_delx_delq4b
    REAL*8 :: sum_dely_delq1, sum_dely_delq2, sum_dely_delq3, &
&   sum_dely_delq4
    REAL*8 :: sum_dely_delq1b, sum_dely_delq2b, sum_dely_delq3b, &
&   sum_dely_delq4b
    REAL*8 :: q1, q2, q3, q4
    REAL*8 :: q1b, q2b, q3b, q4b
    REAL*8 :: temp1, temp2
    REAL*8 :: temp1b, temp2b
    INTRINSIC DSQRT
    REAL*8 :: tempb
    REAL*8 :: tempb0
    REAL*8 :: tempb1
    REAL*8 :: tempb2
    REAL*8 :: tempb3
    REAL*8 :: tempb4
    REAL*8 :: tempb5
    REAL*8 :: tempb6
    REAL*8 :: tempb7
    REAL*8 :: tempb8
    REAL*8 :: tempb9
    REAL*8 :: tempb10
    REAL*8 :: tempb11
    REAL*8 :: tempb12
    REAL*8 :: tempb13
    REAL*8 :: tempb14
    INTEGER :: ad_to
    DO i=1,max_points
      x_i = point%x(i)
      y_i = point%y(i)
      CALL PUSHREAL8(sum_delx_sqr)
      sum_delx_sqr = 0.d0
      CALL PUSHREAL8(sum_dely_sqr)
      sum_dely_sqr = 0.d0
      CALL PUSHREAL8(sum_delx_dely)
      sum_delx_dely = 0.d0
      DO k=1,point%nbhs(i)
        nbh = point%conn(i, k)
        x_k = point%x(nbh)
        y_k = point%y(nbh)
        delx = x_k - x_i
        dely = y_k - y_i
        dist = DSQRT(delx*delx + dely*dely)
        CALL PUSHREAL8(weights)
        weights = dist**power
        sum_delx_sqr = sum_delx_sqr + delx*delx*weights
        sum_dely_sqr = sum_dely_sqr + dely*dely*weights
        sum_delx_dely = sum_delx_dely + delx*dely*weights
      END DO
      CALL PUSHINTEGER4(k - 1)
      det = sum_delx_sqr*sum_dely_sqr - sum_delx_dely*sum_delx_dely
      CALL PUSHREAL8(one_by_det)
      one_by_det = 1.0d0/det
    END DO
    DO i=max_points,1,-1
      sum_dely_delq4b = one_by_det*sum_delx_sqr*pointb%temp(2, 4, i)
      sum_delx_delq4b = -(one_by_det*sum_delx_dely*pointb%temp(2, 4, i))
      pointb%temp(2, 4, i) = 0.0_8
      sum_dely_delq3b = one_by_det*sum_delx_sqr*pointb%temp(2, 3, i)
      sum_delx_delq3b = -(one_by_det*sum_delx_dely*pointb%temp(2, 3, i))
      pointb%temp(2, 3, i) = 0.0_8
      sum_dely_delq2b = one_by_det*sum_delx_sqr*pointb%temp(2, 2, i)
      sum_delx_delq2b = -(one_by_det*sum_delx_dely*pointb%temp(2, 2, i))
      pointb%temp(2, 2, i) = 0.0_8
      sum_dely_delq1b = one_by_det*sum_delx_sqr*pointb%temp(2, 1, i)
      sum_delx_delq1b = -(one_by_det*sum_delx_dely*pointb%temp(2, 1, i))
      pointb%temp(2, 1, i) = 0.0_8
      sum_delx_delq4b = sum_delx_delq4b + one_by_det*sum_dely_sqr*pointb&
&       %temp(1, 4, i)
      sum_dely_delq4b = sum_dely_delq4b - one_by_det*sum_delx_dely*&
&       pointb%temp(1, 4, i)
      pointb%temp(1, 4, i) = 0.0_8
      sum_delx_delq3b = sum_delx_delq3b + one_by_det*sum_dely_sqr*pointb&
&       %temp(1, 3, i)
      sum_dely_delq3b = sum_dely_delq3b - one_by_det*sum_delx_dely*&
&       pointb%temp(1, 3, i)
      pointb%temp(1, 3, i) = 0.0_8
      sum_delx_delq2b = sum_delx_delq2b + one_by_det*sum_dely_sqr*pointb&
&       %temp(1, 2, i)
      sum_dely_delq2b = sum_dely_delq2b - one_by_det*sum_delx_dely*&
&       pointb%temp(1, 2, i)
      pointb%temp(1, 2, i) = 0.0_8
      sum_delx_delq1b = sum_delx_delq1b + one_by_det*sum_dely_sqr*pointb&
&       %temp(1, 1, i)
      sum_dely_delq1b = sum_dely_delq1b - one_by_det*sum_delx_dely*&
&       pointb%temp(1, 1, i)
      pointb%temp(1, 1, i) = 0.0_8
      CALL POPREAL8(one_by_det)
      y_i = point%y(i)
      x_i = point%x(i)
      q1b = 0.0_8
      q2b = 0.0_8
      q3b = 0.0_8
      q4b = 0.0_8
      CALL POPINTEGER4(ad_to)
      DO k=ad_to,1,-1
        nbh = point%conn(i, k)
        y_k = point%y(nbh)
        dely = y_k - y_i
        tempb = weights*dely*sum_dely_delq4b
        x_k = point%x(nbh)
        delx = x_k - x_i
        tempb0 = weights*delx*sum_delx_delq4b
        temp2b = tempb0 + tempb
        temp1b = -tempb0 - tempb
        tempb1 = delx*2*dely**3*temp2b/12.0d0
        pointb%q(4, nbh) = pointb%q(4, nbh) + temp2b
        pointb%dq(1, 4, nbh) = pointb%dq(1, 4, nbh) - 0.5d0*delx*temp2b
        pointb%dq(2, 4, nbh) = pointb%dq(2, 4, nbh) - 0.5d0*dely*temp2b
        pointb%ddq(1, 4, nbh) = pointb%ddq(1, 4, nbh) + delx**2*temp2b/&
&         12.0d0
        pointb%ddq(2, 4, nbh) = pointb%ddq(2, 4, nbh) + point%ddq(3, 4, &
&         nbh)*tempb1
        pointb%ddq(3, 4, nbh) = pointb%ddq(3, 4, nbh) + point%ddq(2, 4, &
&         nbh)*tempb1
        tempb2 = delx*2.0d0*dely**3*temp1b/12.0d0
        q4b = q4b + temp1b
        pointb%dq(1, 4, i) = pointb%dq(1, 4, i) - 0.5d0*delx*temp1b
        pointb%dq(2, 4, i) = pointb%dq(2, 4, i) - 0.5d0*dely*temp1b
        pointb%ddq(1, 4, i) = pointb%ddq(1, 4, i) + delx**2*temp1b/&
&         12.0d0
        pointb%ddq(2, 4, i) = pointb%ddq(2, 4, i) + point%ddq(3, 4, i)*&
&         tempb2
        pointb%ddq(3, 4, i) = pointb%ddq(3, 4, i) + point%ddq(2, 4, i)*&
&         tempb2
        tempb3 = weights*dely*sum_dely_delq3b
        tempb4 = weights*delx*sum_delx_delq3b
        temp2b = tempb4 + tempb3
        temp1b = -tempb4 - tempb3
        tempb5 = delx*2*dely**3*temp2b/12.0d0
        pointb%q(3, nbh) = pointb%q(3, nbh) + temp2b
        pointb%dq(1, 3, nbh) = pointb%dq(1, 3, nbh) - 0.5d0*delx*temp2b
        pointb%dq(2, 3, nbh) = pointb%dq(2, 3, nbh) - 0.5d0*dely*temp2b
        pointb%ddq(1, 3, nbh) = pointb%ddq(1, 3, nbh) + delx**2*temp2b/&
&         12.0d0
        pointb%ddq(2, 3, nbh) = pointb%ddq(2, 3, nbh) + point%ddq(3, 3, &
&         nbh)*tempb5
        pointb%ddq(3, 3, nbh) = pointb%ddq(3, 3, nbh) + point%ddq(2, 3, &
&         nbh)*tempb5
        tempb6 = delx*2.0d0*dely**3*temp1b/12.0d0
        q3b = q3b + temp1b
        pointb%dq(1, 3, i) = pointb%dq(1, 3, i) - 0.5d0*delx*temp1b
        pointb%dq(2, 3, i) = pointb%dq(2, 3, i) - 0.5d0*dely*temp1b
        pointb%ddq(1, 3, i) = pointb%ddq(1, 3, i) + delx**2*temp1b/&
&         12.0d0
        pointb%ddq(2, 3, i) = pointb%ddq(2, 3, i) + point%ddq(3, 3, i)*&
&         tempb6
        pointb%ddq(3, 3, i) = pointb%ddq(3, 3, i) + point%ddq(2, 3, i)*&
&         tempb6
        tempb7 = weights*dely*sum_dely_delq2b
        tempb8 = weights*delx*sum_delx_delq2b
        temp2b = tempb8 + tempb7
        temp1b = -tempb8 - tempb7
        tempb9 = delx*2*dely**3*temp2b/12.0d0
        pointb%q(2, nbh) = pointb%q(2, nbh) + temp2b
        pointb%dq(1, 2, nbh) = pointb%dq(1, 2, nbh) - 0.5d0*delx*temp2b
        pointb%dq(2, 2, nbh) = pointb%dq(2, 2, nbh) - 0.5d0*dely*temp2b
        pointb%ddq(1, 2, nbh) = pointb%ddq(1, 2, nbh) + delx**2*temp2b/&
&         12.0d0
        pointb%ddq(2, 2, nbh) = pointb%ddq(2, 2, nbh) + point%ddq(3, 2, &
&         nbh)*tempb9
        pointb%ddq(3, 2, nbh) = pointb%ddq(3, 2, nbh) + point%ddq(2, 2, &
&         nbh)*tempb9
        tempb10 = delx*2.0d0*dely**3*temp1b/12.0d0
        q2b = q2b + temp1b
        pointb%dq(1, 2, i) = pointb%dq(1, 2, i) - 0.5d0*delx*temp1b
        pointb%dq(2, 2, i) = pointb%dq(2, 2, i) - 0.5d0*dely*temp1b
        pointb%ddq(1, 2, i) = pointb%ddq(1, 2, i) + delx**2*temp1b/&
&         12.0d0
        pointb%ddq(2, 2, i) = pointb%ddq(2, 2, i) + point%ddq(3, 2, i)*&
&         tempb10
        pointb%ddq(3, 2, i) = pointb%ddq(3, 2, i) + point%ddq(2, 2, i)*&
&         tempb10
        tempb11 = weights*dely*sum_dely_delq1b
        tempb12 = weights*delx*sum_delx_delq1b
        temp2b = tempb12 + tempb11
        temp1b = -tempb12 - tempb11
        tempb13 = delx*2*dely**3*temp2b/12.0d0
        pointb%q(1, nbh) = pointb%q(1, nbh) + temp2b
        pointb%dq(1, 1, nbh) = pointb%dq(1, 1, nbh) - 0.5d0*delx*temp2b
        pointb%dq(2, 1, nbh) = pointb%dq(2, 1, nbh) - 0.5d0*dely*temp2b
        pointb%ddq(1, 1, nbh) = pointb%ddq(1, 1, nbh) + delx**2*temp2b/&
&         12.0d0
        pointb%ddq(2, 1, nbh) = pointb%ddq(2, 1, nbh) + point%ddq(3, 1, &
&         nbh)*tempb13
        pointb%ddq(3, 1, nbh) = pointb%ddq(3, 1, nbh) + point%ddq(2, 1, &
&         nbh)*tempb13
        tempb14 = delx*2.0d0*dely**3*temp1b/12.0d0
        q1b = q1b + temp1b
        pointb%dq(1, 1, i) = pointb%dq(1, 1, i) - 0.5d0*delx*temp1b
        pointb%dq(2, 1, i) = pointb%dq(2, 1, i) - 0.5d0*dely*temp1b
        pointb%ddq(1, 1, i) = pointb%ddq(1, 1, i) + delx**2*temp1b/&
&         12.0d0
        pointb%ddq(2, 1, i) = pointb%ddq(2, 1, i) + point%ddq(3, 1, i)*&
&         tempb14
        pointb%ddq(3, 1, i) = pointb%ddq(3, 1, i) + point%ddq(2, 1, i)*&
&         tempb14
        CALL POPREAL8(weights)
      END DO
      pointb%q(4, i) = pointb%q(4, i) + q4b
      pointb%q(3, i) = pointb%q(3, i) + q3b
      pointb%q(2, i) = pointb%q(2, i) + q2b
      pointb%q(1, i) = pointb%q(1, i) + q1b
      CALL POPREAL8(sum_delx_dely)
      CALL POPREAL8(sum_dely_sqr)
      CALL POPREAL8(sum_delx_sqr)
    END DO
  END SUBROUTINE EVAL_Q_INNER_LOOP_B

  SUBROUTINE EVAL_Q_INNER_LOOP()
    IMPLICIT NONE
    INTEGER :: i
    INTEGER :: k, r, nbh
    REAL*8 :: x_i, y_i, x_k, y_k
    REAL*8 :: delx, dely, dist, weights
    REAL*8 :: sum_delx_sqr, sum_dely_sqr, sum_delx_dely
    REAL*8 :: det, temp
    REAL*8 :: one_by_det
    REAL*8 :: sum_delx_delq1, sum_delx_delq2, sum_delx_delq3, &
&   sum_delx_delq4
    REAL*8 :: sum_dely_delq1, sum_dely_delq2, sum_dely_delq3, &
&   sum_dely_delq4
    REAL*8 :: q1, q2, q3, q4
    REAL*8 :: temp1, temp2
    ! INTRINSIC DSQRT
    DO i=1,max_points
      x_i = point%x(i)
      y_i = point%y(i)
      sum_delx_sqr = 0.d0
      sum_dely_sqr = 0.d0
      sum_delx_dely = 0.d0
      temp1 = 0.d0
      temp2 = 0.d0
      sum_delx_delq1 = 0.d0
      sum_delx_delq2 = 0.d0
      sum_delx_delq3 = 0.d0
      sum_delx_delq4 = 0.d0
      sum_dely_delq1 = 0.d0
      sum_dely_delq2 = 0.d0
      sum_dely_delq3 = 0.d0
      sum_dely_delq4 = 0.d0
      q1 = point%q(1, i)
      q2 = point%q(2, i)
      q3 = point%q(3, i)
      q4 = point%q(4, i)
      DO k=1,point%nbhs(i)
        nbh = point%conn(i, k)
        x_k = point%x(nbh)
        y_k = point%y(nbh)
        delx = x_k - x_i
        dely = y_k - y_i
        dist = DSQRT(delx*delx + dely*dely)
        weights = dist**power
        sum_delx_sqr = sum_delx_sqr + delx*delx*weights
        sum_dely_sqr = sum_dely_sqr + dely*dely*weights
        sum_delx_dely = sum_delx_dely + delx*dely*weights
        temp1 = q1 - 0.5d0*(delx*point%dq(1, 1, i)+dely*point%dq(2, 1, i&
&         )) + 1.0d0/12.0d0*(delx*delx*point%ddq(1, 1, i)+2.0d0*delx*&
&         dely*point%ddq(2, 1, i)*dely*dely*point%ddq(3, 1, i))
        temp2 = point%q(1, nbh) - 0.5d0*(delx*point%dq(1, 1, nbh)+dely*&
&         point%dq(2, 1, nbh)) + 1.0d0/12.0d0*(delx*delx*point%ddq(1, 1&
&         , nbh)+2*delx*dely*point%ddq(2, 1, nbh)*dely*dely*point%ddq(3&
&         , 1, nbh))
        sum_delx_delq1 = sum_delx_delq1 + weights*delx*(temp2-temp1)
        sum_dely_delq1 = sum_dely_delq1 + weights*dely*(temp2-temp1)
        temp1 = q2 - 0.5d0*(delx*point%dq(1, 2, i)+dely*point%dq(2, 2, i&
&         )) + 1.0d0/12.0d0*(delx*delx*point%ddq(1, 2, i)+2.0d0*delx*&
&         dely*point%ddq(2, 2, i)*dely*dely*point%ddq(3, 2, i))
        temp2 = point%q(2, nbh) - 0.5d0*(delx*point%dq(1, 2, nbh)+dely*&
&         point%dq(2, 2, nbh)) + 1.0d0/12.0d0*(delx*delx*point%ddq(1, 2&
&         , nbh)+2*delx*dely*point%ddq(2, 2, nbh)*dely*dely*point%ddq(3&
&         , 2, nbh))
        sum_delx_delq2 = sum_delx_delq2 + weights*delx*(temp2-temp1)
        sum_dely_delq2 = sum_dely_delq2 + weights*dely*(temp2-temp1)
        temp1 = q3 - 0.5d0*(delx*point%dq(1, 3, i)+dely*point%dq(2, 3, i&
&         )) + 1.0d0/12.0d0*(delx*delx*point%ddq(1, 3, i)+2.0d0*delx*&
&         dely*point%ddq(2, 3, i)*dely*dely*point%ddq(3, 3, i))
        temp2 = point%q(3, nbh) - 0.5d0*(delx*point%dq(1, 3, nbh)+dely*&
&         point%dq(2, 3, nbh)) + 1.0d0/12.0d0*(delx*delx*point%ddq(1, 3&
&         , nbh)+2*delx*dely*point%ddq(2, 3, nbh)*dely*dely*point%ddq(3&
&         , 3, nbh))
        sum_delx_delq3 = sum_delx_delq3 + weights*delx*(temp2-temp1)
        sum_dely_delq3 = sum_dely_delq3 + weights*dely*(temp2-temp1)
        temp1 = q4 - 0.5d0*(delx*point%dq(1, 4, i)+dely*point%dq(2, 4, i&
&         )) + 1.0d0/12.0d0*(delx*delx*point%ddq(1, 4, i)+2.0d0*delx*&
&         dely*point%ddq(2, 4, i)*dely*dely*point%ddq(3, 4, i))
        temp2 = point%q(4, nbh) - 0.5d0*(delx*point%dq(1, 4, nbh)+dely*&
&         point%dq(2, 4, nbh)) + 1.0d0/12.0d0*(delx*delx*point%ddq(1, 4&
&         , nbh)+2*delx*dely*point%ddq(2, 4, nbh)*dely*dely*point%ddq(3&
&         , 4, nbh))
        sum_delx_delq4 = sum_delx_delq4 + weights*delx*(temp2-temp1)
        sum_dely_delq4 = sum_dely_delq4 + weights*dely*(temp2-temp1)
      END DO
      det = sum_delx_sqr*sum_dely_sqr - sum_delx_dely*sum_delx_dely
      one_by_det = 1.0d0/det
      point%temp(1, 1, i) = one_by_det*(sum_delx_delq1*sum_dely_sqr-&
&       sum_dely_delq1*sum_delx_dely)
      point%temp(1, 2, i) = one_by_det*(sum_delx_delq2*sum_dely_sqr-&
&       sum_dely_delq2*sum_delx_dely)
      point%temp(1, 3, i) = one_by_det*(sum_delx_delq3*sum_dely_sqr-&
&       sum_dely_delq3*sum_delx_dely)
      point%temp(1, 4, i) = one_by_det*(sum_delx_delq4*sum_dely_sqr-&
&       sum_dely_delq4*sum_delx_dely)
      point%temp(2, 1, i) = one_by_det*(sum_dely_delq1*sum_delx_sqr-&
&       sum_delx_delq1*sum_delx_dely)
      point%temp(2, 2, i) = one_by_det*(sum_dely_delq2*sum_delx_sqr-&
&       sum_delx_delq2*sum_delx_dely)
      point%temp(2, 3, i) = one_by_det*(sum_dely_delq3*sum_delx_sqr-&
&       sum_delx_delq3*sum_delx_dely)
      point%temp(2, 4, i) = one_by_det*(sum_dely_delq4*sum_delx_sqr-&
&       sum_delx_delq4*sum_delx_dely)
    END DO
  END SUBROUTINE EVAL_Q_INNER_LOOP

  SUBROUTINE EVAL_UPDATE_INNERLOOP_B()
    IMPLICIT NONE
    INTEGER :: i
    DO i=max_points,1,-1
      pointb%temp(2, 4, i) = pointb%temp(2, 4, i) + pointb%dq(2, 4, i)
      pointb%dq(2, 4, i) = 0.0_8
      pointb%temp(2, 3, i) = pointb%temp(2, 3, i) + pointb%dq(2, 3, i)
      pointb%dq(2, 3, i) = 0.0_8
      pointb%temp(2, 2, i) = pointb%temp(2, 2, i) + pointb%dq(2, 2, i)
      pointb%dq(2, 2, i) = 0.0_8
      pointb%temp(2, 1, i) = pointb%temp(2, 1, i) + pointb%dq(2, 1, i)
      pointb%dq(2, 1, i) = 0.0_8
      pointb%temp(1, 4, i) = pointb%temp(1, 4, i) + pointb%dq(1, 4, i)
      pointb%dq(1, 4, i) = 0.0_8
      pointb%temp(1, 3, i) = pointb%temp(1, 3, i) + pointb%dq(1, 3, i)
      pointb%dq(1, 3, i) = 0.0_8
      pointb%temp(1, 2, i) = pointb%temp(1, 2, i) + pointb%dq(1, 2, i)
      pointb%dq(1, 2, i) = 0.0_8
      pointb%temp(1, 1, i) = pointb%temp(1, 1, i) + pointb%dq(1, 1, i)
      pointb%dq(1, 1, i) = 0.0_8
    END DO
  END SUBROUTINE EVAL_UPDATE_INNERLOOP_B

  SUBROUTINE EVAL_UPDATE_INNERLOOP()
    IMPLICIT NONE
    INTEGER :: i
    DO i=1,max_points
      point%dq(1, 1, i) = point%temp(1, 1, i)
      point%dq(1, 2, i) = point%temp(1, 2, i)
      point%dq(1, 3, i) = point%temp(1, 3, i)
      point%dq(1, 4, i) = point%temp(1, 4, i)
      point%dq(2, 1, i) = point%temp(2, 1, i)
      point%dq(2, 2, i) = point%temp(2, 2, i)
      point%dq(2, 3, i) = point%temp(2, 3, i)
      point%dq(2, 4, i) = point%temp(2, 4, i)
    END DO
  END SUBROUTINE EVAL_UPDATE_INNERLOOP

!  Differentiation of qtilde_to_primitive in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: u1 u2 pr rho
!   with respect to varying inputs: qtilde
  SUBROUTINE QTILDE_TO_PRIMITIVE_B(qtilde, qtildeb, u1, u1b, u2, u2b, &
&   rho, rhob, pr, prb)
    IMPLICIT NONE
    REAL*8 :: qtilde(4), u1, u2, rho, pr
    REAL*8 :: qtildeb(4), u1b, u2b, rhob, prb
    REAL*8 :: beta, temp, temp1, temp2
    REAL*8 :: betab, tempb, temp1b, temp2b
    REAL*8 :: q1, q2, q3, q4
    REAL*8 :: q1b, q2b, q3b, q4b
    INTRINSIC DLOG
    INTRINSIC DEXP
    q1 = qtilde(1)
    q2 = qtilde(2)
    q3 = qtilde(3)
    q4 = qtilde(4)
    beta = -(q4*0.5d0)
    temp = 0.5d0/beta
    CALL PUSHREAL8(u1)
    u1 = q2*temp
    CALL PUSHREAL8(u2)
    u2 = q3*temp
    temp1 = q1 + beta*(u1*u1+u2*u2)
    temp2 = temp1 - DLOG(beta)/(gamma-1)
    CALL PUSHREAL8(rho)
    rho = DEXP(temp2)
    rhob = rhob + temp*prb
    temp2b = DEXP(temp2)*rhob
    temp1b = temp2b
    q1b = temp1b
    u1b = u1b + beta*2*u1*temp1b
    u2b = u2b + beta*2*u2*temp1b
    tempb = q3*u2b + q2*u1b + rho*prb
    CALL POPREAL8(rho)
    betab = (u1**2+u2**2)*temp1b - 0.5d0*tempb/beta**2 - temp2b/((gamma-&
&     1)*beta)
    CALL POPREAL8(u2)
    q3b = temp*u2b
    CALL POPREAL8(u1)
    q2b = temp*u1b
    q4b = -(0.5d0*betab)
    qtildeb = 0.0_8
    qtildeb(4) = qtildeb(4) + q4b
    qtildeb(3) = qtildeb(3) + q3b
    qtildeb(2) = qtildeb(2) + q2b
    qtildeb(1) = qtildeb(1) + q1b
  END SUBROUTINE QTILDE_TO_PRIMITIVE_B

  SUBROUTINE QTILDE_TO_PRIMITIVE(qtilde, u1, u2, rho, pr)
    IMPLICIT NONE
    REAL*8 :: qtilde(4), u1, u2, rho, pr
    REAL*8 :: beta, temp, temp1, temp2
    REAL*8 :: q1, q2, q3, q4
    ! INTRINSIC DLOG
    ! INTRINSIC DEXP
    q1 = qtilde(1)
    q2 = qtilde(2)
    q3 = qtilde(3)
    q4 = qtilde(4)
    beta = -(q4*0.5d0)
    temp = 0.5d0/beta
    u1 = q2*temp
    u2 = q3*temp
    temp1 = q1 + beta*(u1*u1+u2*u2)
    temp2 = temp1 - DLOG(beta)/(gamma-1)
    rho = DEXP(temp2)
    pr = rho*temp
  END SUBROUTINE QTILDE_TO_PRIMITIVE

END MODULE Q_VARIABLES_MOD_DIFF
