1 Command: Command-line option -vars is deprecated: please use -head instead
2 Command: Command-line option -outvars is deprecated: please use -head instead
3 Command: Procedure q_lskum understood as q_lskum_mod.q_lskum
4 q_lskum_mod: (DD15) Module initial_conditions_mod is not defined
5 q_lskum_mod: (DD15) Module ieee_arithmetic is not defined
6 fpi_solver_mod: (DD15) Module post_processing_mod is not defined
7 fpi_solver: (TC33) External procedure print_primal_output is not declared
8 (DF05) External routine print_primal_output, called by (fpi_solver), is assumed default In:. and Out:.
9 state_update_mod: (DD15) Module petsc_data_structure_mod is not defined
10 conserved_vector_ubar: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
11 conserved_vector_ubar: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
12 generate_connectivity_mod: (DD15) Module petsc_data_structure_mod is not defined
13 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
14 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
15 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
16 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
17 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
18 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
19 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
20 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
21 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
22 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
23 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
24 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
25 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
26 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
27 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
28 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
29 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
30 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
31 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
32 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
33 flux_gxp: (TC33) External procedure derf is not declared
34 flux_gxp: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
35 flux_gxn: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
36 flux_gyp: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
37 flux_gyn: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
38 flux_quad_gxi: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
39 flux_quad_gxi: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
40 flux_quad_gxii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
41 flux_quad_gxii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
42 flux_quad_gxiii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
43 flux_quad_gxiii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
44 flux_quad_gxiv: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
45 flux_quad_gxiv: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
46 (DF05) External routine derf, called by (flux_gxp flux_gxn flux_gyp flux_gyn conserved_vector_ubar flux_quad_gxi flux_quad_gxii flux_quad_gxiii flux_quad_gxiv), is assumed default In:.1. and Out:.11
47 compute_force_coeffs_mod: (DD15) Module petsc_data_structure_mod is not defined
48 compute_cl_cd_cm: (TC20) Variable proc is not declared
49 compute_cl_cd_cm: (TC24) Wrong number of dimensions for array itos: 1 expected, and 2 given
50 compute_cl_cd_cm: (DF03) variable proc is used before initialized
51 compute_cl_cd_cm: (AD03) Varied variable cp written by I-O to file 201
52 compute_cl_cd_cm: (AD03) Varied variable *(point.x)[m] written by I-O to file 201
53 compute_entropy_mod: (DD15) Module petsc_data_structure_mod is not defined
54 compute_enstrophy_mod: (DD15) Module petsc_data_structure_mod is not defined
55 stagnation_values_mod: (DD15) Module petsc_data_structure_mod is not defined
56 data_structure_mod: (DD28) Save statement may save extra variables, please use "save::varname" 
57 compute_cl_cd_cm_d: Tool: (TypeSpec tree regeneration) null wrapped type
58 compute_cl_cd_cm: Tool: (TypeSpec tree regeneration) null wrapped type
