!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.14 (r7259) - 18 Jan 2019 09:36
!
MODULE SPLIT_FLUXES_MOD_DIFF
  USE PARAMETER_MOD
  IMPLICIT NONE

CONTAINS
!  Differentiation of flux_gxp in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: gxp
!   with respect to varying inputs: gxp u1 u2 pr rho
  SUBROUTINE FLUX_GXP_D(gxp, gxpd, nx, ny, u1, u1d, u2, u2d, rho, rhod&
&   , pr, prd)
    IMPLICIT NONE
    DOUBLE PRECISION :: gxp(4), u1, u2, rho, pr
    DOUBLE PRECISION :: gxpd(4), u1d, u2d, rhod, prd
    DOUBLE PRECISION :: tx, ty, nx, ny, ut, un
    DOUBLE PRECISION :: utd, und
    DOUBLE PRECISION :: beta, s1, b1, a1pos
    DOUBLE PRECISION :: betad, s1d, b1d, a1posd
    DOUBLE PRECISION :: temp1, temp2
    DOUBLE PRECISION :: temp1d, temp2d
    DOUBLE PRECISION :: pr_by_rho, u_sqr
    DOUBLE PRECISION :: pr_by_rhod, u_sqrd
    ! DOUBLE PRECISION :: DERF
    ! DOUBLE PRECISION :: DERF_D
    ! INTRINSIC DSQRT
    ! INTRINSIC DEXP
    ! EXTERNAL DERF
    ! EXTERNAL DERF_D
    DOUBLE PRECISION :: result1
    DOUBLE PRECISION :: result1d
    REAL*8 :: arg1
    REAL*8 :: arg1d
    tx = ny
    ty = -nx
    utd = tx*u1d + ty*u2d
    ut = u1*tx + u2*ty
    und = nx*u1d + ny*u2d
    un = u1*nx + u2*ny
    betad = (0.5d0*rhod*pr-0.5d0*rho*prd)/pr**2
    beta = 0.5d0*rho/pr
    IF (beta .EQ. 0.0) THEN
      result1d = 0.D0
    ELSE
      result1d = betad/(2.D0*DSQRT(beta))
    END IF
    result1 = DSQRT(beta)
    s1d = utd*result1 + ut*result1d
    s1 = ut*result1
    arg1d = pi*betad
    arg1 = pi*beta
    IF (arg1 .EQ. 0.0) THEN
      result1d = 0.D0
    ELSE
      result1d = arg1d/(2.D0*DSQRT(arg1))
    END IF
    result1 = DSQRT(arg1)
    b1d = (-(0.5d0*(s1d*s1+s1*s1d)*DEXP(-(s1*s1))*result1)-0.5d0*DEXP(-(&
&     s1*s1))*result1d)/result1**2
    b1 = 0.5d0*DEXP(-(s1*s1))/result1

    ! result1d = DERF_D(s1, s1d, result1)

    result1d = dexp(-s1**2)*(2.d0/sqrt(pi))*s1d
    result1 = derf(s1)

    a1posd = 0.5d0*result1d
    a1pos = 0.5d0*(1.0d0+result1)
    pr_by_rhod = (prd*rho-pr*rhod)/rho**2
    pr_by_rho = pr/rho
    u_sqrd = utd*ut + ut*utd + und*un + un*und
    u_sqr = ut*ut + un*un
!     Expressions for the split fluxes ..
    gxpd(1) = rhod*(ut*a1pos+b1) + rho*(utd*a1pos+ut*a1posd+b1d)
    gxp(1) = rho*(ut*a1pos+b1)
    temp1d = pr_by_rhod + utd*ut + ut*utd
    temp1 = pr_by_rho + ut*ut
    temp2d = temp1d*a1pos + temp1*a1posd + utd*b1 + ut*b1d
    temp2 = temp1*a1pos + ut*b1
    gxpd(2) = rhod*temp2 + rho*temp2d
    gxp(2) = rho*temp2
    temp1d = (utd*un+ut*und)*a1pos + ut*un*a1posd + und*b1 + un*b1d
    temp1 = ut*un*a1pos + un*b1
    gxpd(3) = rhod*temp1 + rho*temp1d
    gxp(3) = rho*temp1
    temp1d = 7.0d0*pr_by_rhod + u_sqrd
    temp1 = 7.0d0*pr_by_rho + u_sqr
    temp2d = 0.5d0*((utd*temp1+ut*temp1d)*a1pos+ut*temp1*a1posd)
    temp2 = 0.5d0*ut*temp1*a1pos
    temp1d = 6.0d0*pr_by_rhod + u_sqrd
    temp1 = 6.0d0*pr_by_rho + u_sqr
    gxpd(4) = rhod*(temp2+0.5d0*temp1*b1) + rho*(temp2d+0.5d0*(temp1d*b1&
&     +temp1*b1d))
    gxp(4) = rho*(temp2+0.5d0*temp1*b1)
  END SUBROUTINE FLUX_GXP_D

  SUBROUTINE FLUX_GXP(gxp, nx, ny, u1, u2, rho, pr)
    IMPLICIT NONE
    DOUBLE PRECISION :: gxp(4), u1, u2, rho, pr
    DOUBLE PRECISION :: tx, ty, nx, ny, ut, un
    DOUBLE PRECISION :: beta, s1, b1, a1pos
    DOUBLE PRECISION :: temp1, temp2
    DOUBLE PRECISION :: pr_by_rho, u_sqr
    ! DOUBLE PRECISION :: DERF
    ! INTRINSIC DSQRT
    ! INTRINSIC DEXP
    ! EXTERNAL DERF
    DOUBLE PRECISION :: result1
    REAL*8 :: arg1
    tx = ny
    ty = -nx
    ut = u1*tx + u2*ty
    un = u1*nx + u2*ny
    beta = 0.5d0*rho/pr
    result1 = DSQRT(beta)
    s1 = ut*result1
    arg1 = pi*beta
    result1 = DSQRT(arg1)
    b1 = 0.5d0*DEXP(-(s1*s1))/result1
    result1 = DERF(s1)
    a1pos = 0.5d0*(1.0d0+result1)
    pr_by_rho = pr/rho
    u_sqr = ut*ut + un*un
!     Expressions for the split fluxes ..
    gxp(1) = rho*(ut*a1pos+b1)
    temp1 = pr_by_rho + ut*ut
    temp2 = temp1*a1pos + ut*b1
    gxp(2) = rho*temp2
    temp1 = ut*un*a1pos + un*b1
    gxp(3) = rho*temp1
    temp1 = 7.0d0*pr_by_rho + u_sqr
    temp2 = 0.5d0*ut*temp1*a1pos
    temp1 = 6.0d0*pr_by_rho + u_sqr
    gxp(4) = rho*(temp2+0.5d0*temp1*b1)
  END SUBROUTINE FLUX_GXP

!  Differentiation of flux_gxn in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: gxn
!   with respect to varying inputs: gxn u1 u2 pr rho
  SUBROUTINE FLUX_GXN_D(gxn, gxnd, nx, ny, u1, u1d, u2, u2d, rho, rhod&
&   , pr, prd)
    IMPLICIT NONE
    DOUBLE PRECISION :: gxn(4), u1, u2, rho, pr
    DOUBLE PRECISION :: gxnd(4), u1d, u2d, rhod, prd
    DOUBLE PRECISION :: tx, ty, nx, ny, ut, un
    DOUBLE PRECISION :: utd, und
    DOUBLE PRECISION :: beta, s1, b1, a1neg
    DOUBLE PRECISION :: betad, s1d, b1d, a1negd
    DOUBLE PRECISION :: temp1, temp2
    DOUBLE PRECISION :: temp1d, temp2d
    DOUBLE PRECISION :: pr_by_rho, u_sqr
    DOUBLE PRECISION :: pr_by_rhod, u_sqrd
    ! DOUBLE PRECISION :: DERF
    ! DOUBLE PRECISION :: DERF_D
    ! INTRINSIC DSQRT
    ! INTRINSIC DEXP
    ! EXTERNAL DERF
    ! EXTERNAL DERF_D
    DOUBLE PRECISION :: result1
    DOUBLE PRECISION :: result1d
    REAL*8 :: arg1
    REAL*8 :: arg1d
    tx = ny
    ty = -nx
    utd = tx*u1d + ty*u2d
    ut = u1*tx + u2*ty
    und = nx*u1d + ny*u2d
    un = u1*nx + u2*ny
    betad = (0.5d0*rhod*pr-0.5d0*rho*prd)/pr**2
    beta = 0.5d0*rho/pr
    IF (beta .EQ. 0.0) THEN
      result1d = 0.D0
    ELSE
      result1d = betad/(2.D0*DSQRT(beta))
    END IF
    result1 = DSQRT(beta)
    s1d = utd*result1 + ut*result1d
    s1 = ut*result1
    arg1d = pi*betad
    arg1 = pi*beta
    IF (arg1 .EQ. 0.0) THEN
      result1d = 0.D0
    ELSE
      result1d = arg1d/(2.D0*DSQRT(arg1))
    END IF
    result1 = DSQRT(arg1)
    b1d = (-(0.5d0*(s1d*s1+s1*s1d)*DEXP(-(s1*s1))*result1)-0.5d0*DEXP(-(&
&     s1*s1))*result1d)/result1**2
    b1 = 0.5d0*DEXP(-(s1*s1))/result1
    ! result1d = DERF_D(s1, s1d, result1)

    result1d = dexp(-s1**2)*(2.d0/sqrt(pi))*s1d
    result1 = derf(s1)

    a1negd = -(0.5d0*result1d)
    a1neg = 0.5d0*(1.0d0-result1)
    pr_by_rhod = (prd*rho-pr*rhod)/rho**2
    pr_by_rho = pr/rho
    u_sqrd = utd*ut + ut*utd + und*un + un*und
    u_sqr = ut*ut + un*un
!		Expressions for the split fluxes ..
    gxnd(1) = rhod*(ut*a1neg-b1) + rho*(utd*a1neg+ut*a1negd-b1d)
    gxn(1) = rho*(ut*a1neg-b1)
    temp1d = pr_by_rhod + utd*ut + ut*utd
    temp1 = pr_by_rho + ut*ut
    temp2d = temp1d*a1neg + temp1*a1negd - utd*b1 - ut*b1d
    temp2 = temp1*a1neg - ut*b1
    gxnd(2) = rhod*temp2 + rho*temp2d
    gxn(2) = rho*temp2
    temp1d = (utd*un+ut*und)*a1neg + ut*un*a1negd - und*b1 - un*b1d
    temp1 = ut*un*a1neg - un*b1
    gxnd(3) = rhod*temp1 + rho*temp1d
    gxn(3) = rho*temp1
    temp1d = 7.0d0*pr_by_rhod + u_sqrd
    temp1 = 7.0d0*pr_by_rho + u_sqr
    temp2d = 0.5d0*((utd*temp1+ut*temp1d)*a1neg+ut*temp1*a1negd)
    temp2 = 0.5d0*ut*temp1*a1neg
    temp1d = 6.0d0*pr_by_rhod + u_sqrd
    temp1 = 6.0d0*pr_by_rho + u_sqr
    gxnd(4) = rhod*(temp2-0.5d0*temp1*b1) + rho*(temp2d-0.5d0*(temp1d*b1&
&     +temp1*b1d))
    gxn(4) = rho*(temp2-0.5d0*temp1*b1)
  END SUBROUTINE FLUX_GXN_D

  SUBROUTINE FLUX_GXN(gxn, nx, ny, u1, u2, rho, pr)
    IMPLICIT NONE
    DOUBLE PRECISION :: gxn(4), u1, u2, rho, pr
    DOUBLE PRECISION :: tx, ty, nx, ny, ut, un
    DOUBLE PRECISION :: beta, s1, b1, a1neg
    DOUBLE PRECISION :: temp1, temp2
    DOUBLE PRECISION :: pr_by_rho, u_sqr
    ! DOUBLE PRECISION :: DERF
    ! INTRINSIC DSQRT
    ! INTRINSIC DEXP
    ! EXTERNAL DERF
    DOUBLE PRECISION :: result1
    REAL*8 :: arg1
    tx = ny
    ty = -nx
    ut = u1*tx + u2*ty
    un = u1*nx + u2*ny
    beta = 0.5d0*rho/pr
    result1 = DSQRT(beta)
    s1 = ut*result1
    arg1 = pi*beta
    result1 = DSQRT(arg1)
    b1 = 0.5d0*DEXP(-(s1*s1))/result1
    result1 = DERF(s1)
    a1neg = 0.5d0*(1.0d0-result1)
    pr_by_rho = pr/rho
    u_sqr = ut*ut + un*un
!		Expressions for the split fluxes ..
    gxn(1) = rho*(ut*a1neg-b1)
    temp1 = pr_by_rho + ut*ut
    temp2 = temp1*a1neg - ut*b1
    gxn(2) = rho*temp2
    temp1 = ut*un*a1neg - un*b1
    gxn(3) = rho*temp1
    temp1 = 7.0d0*pr_by_rho + u_sqr
    temp2 = 0.5d0*ut*temp1*a1neg
    temp1 = 6.0d0*pr_by_rho + u_sqr
    gxn(4) = rho*(temp2-0.5d0*temp1*b1)
  END SUBROUTINE FLUX_GXN

!  Differentiation of flux_gyp in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: gyp
!   with respect to varying inputs: gyp u1 u2 pr rho
  SUBROUTINE FLUX_GYP_D(gyp, gypd, nx, ny, u1, u1d, u2, u2d, rho, rhod&
&   , pr, prd)
    IMPLICIT NONE
    DOUBLE PRECISION :: gyp(4), u1, u2, rho, pr
    DOUBLE PRECISION :: gypd(4), u1d, u2d, rhod, prd
    DOUBLE PRECISION :: tx, ty, nx, ny, ut, un
    DOUBLE PRECISION :: utd, und
    DOUBLE PRECISION :: beta, s2, b2, a2pos
    DOUBLE PRECISION :: betad, s2d, b2d, a2posd
    DOUBLE PRECISION :: temp1, temp2
    DOUBLE PRECISION :: temp1d, temp2d
    DOUBLE PRECISION :: pr_by_rho, u_sqr
    DOUBLE PRECISION :: pr_by_rhod, u_sqrd
    ! DOUBLE PRECISION :: DERF
    ! DOUBLE PRECISION :: DERF_D
    ! INTRINSIC DSQRT
    ! INTRINSIC DEXP
    ! EXTERNAL DERF
    ! EXTERNAL DERF_D
    DOUBLE PRECISION :: result1
    DOUBLE PRECISION :: result1d
    REAL*8 :: arg1
    REAL*8 :: arg1d
    tx = ny
    ty = -nx
    utd = tx*u1d + ty*u2d
    ut = u1*tx + u2*ty
    und = nx*u1d + ny*u2d
    un = u1*nx + u2*ny
    betad = (0.5d0*rhod*pr-0.5d0*rho*prd)/pr**2
    beta = 0.5d0*rho/pr
    IF (beta .EQ. 0.0) THEN
      result1d = 0.D0
    ELSE
      result1d = betad/(2.D0*DSQRT(beta))
    END IF
    result1 = DSQRT(beta)
    s2d = und*result1 + un*result1d
    s2 = un*result1
    arg1d = pi*betad
    arg1 = pi*beta
    IF (arg1 .EQ. 0.0) THEN
      result1d = 0.D0
    ELSE
      result1d = arg1d/(2.D0*DSQRT(arg1))
    END IF
    result1 = DSQRT(arg1)
    b2d = (-(0.5d0*(s2d*s2+s2*s2d)*DEXP(-(s2*s2))*result1)-0.5d0*DEXP(-(&
&     s2*s2))*result1d)/result1**2
    b2 = 0.5d0*DEXP(-(s2*s2))/result1

    ! result1d = DERF_D(s2, s2d, result1)
    result1d = dexp(-s2**2)*(2.d0/sqrt(pi))*s2d
    result1 = derf(s2)

    a2posd = 0.5d0*result1d
    a2pos = 0.5d0*(1.0d0+result1)
    pr_by_rhod = (prd*rho-pr*rhod)/rho**2
    pr_by_rho = pr/rho
    u_sqrd = utd*ut + ut*utd + und*un + un*und
    u_sqr = ut*ut + un*un
!		Expressions for the split fluxes ..
    gypd(1) = rhod*(un*a2pos+b2) + rho*(und*a2pos+un*a2posd+b2d)
    gyp(1) = rho*(un*a2pos+b2)
    temp1d = pr_by_rhod + und*un + un*und
    temp1 = pr_by_rho + un*un
    temp2d = temp1d*a2pos + temp1*a2posd + und*b2 + un*b2d
    temp2 = temp1*a2pos + un*b2
    gypd(3) = rhod*temp2 + rho*temp2d
    gyp(3) = rho*temp2
    temp1d = (utd*un+ut*und)*a2pos + ut*un*a2posd + utd*b2 + ut*b2d
    temp1 = ut*un*a2pos + ut*b2
    gypd(2) = rhod*temp1 + rho*temp1d
    gyp(2) = rho*temp1
    temp1d = 7.0d0*pr_by_rhod + u_sqrd
    temp1 = 7.0d0*pr_by_rho + u_sqr
    temp2d = 0.5d0*((und*temp1+un*temp1d)*a2pos+un*temp1*a2posd)
    temp2 = 0.5d0*un*temp1*a2pos
    temp1d = 6.0d0*pr_by_rhod + u_sqrd
    temp1 = 6.0d0*pr_by_rho + u_sqr
    gypd(4) = rhod*(temp2+0.5d0*temp1*b2) + rho*(temp2d+0.5d0*(temp1d*b2&
&     +temp1*b2d))
    gyp(4) = rho*(temp2+0.5d0*temp1*b2)
  END SUBROUTINE FLUX_GYP_D

  SUBROUTINE FLUX_GYP(gyp, nx, ny, u1, u2, rho, pr)
    IMPLICIT NONE
    DOUBLE PRECISION :: gyp(4), u1, u2, rho, pr
    DOUBLE PRECISION :: tx, ty, nx, ny, ut, un
    DOUBLE PRECISION :: beta, s2, b2, a2pos
    DOUBLE PRECISION :: temp1, temp2
    DOUBLE PRECISION :: pr_by_rho, u_sqr
    ! DOUBLE PRECISION :: DERF
    ! INTRINSIC DSQRT
    ! INTRINSIC DEXP
    ! EXTERNAL DERF
    DOUBLE PRECISION :: result1
    REAL*8 :: arg1
    tx = ny
    ty = -nx
    ut = u1*tx + u2*ty
    un = u1*nx + u2*ny
    beta = 0.5d0*rho/pr
    result1 = DSQRT(beta)
    s2 = un*result1
    arg1 = pi*beta
    result1 = DSQRT(arg1)
    b2 = 0.5d0*DEXP(-(s2*s2))/result1
    result1 = DERF(s2)
    a2pos = 0.5d0*(1.0d0+result1)
    pr_by_rho = pr/rho
    u_sqr = ut*ut + un*un
!		Expressions for the split fluxes ..
    gyp(1) = rho*(un*a2pos+b2)
    temp1 = pr_by_rho + un*un
    temp2 = temp1*a2pos + un*b2
    gyp(3) = rho*temp2
    temp1 = ut*un*a2pos + ut*b2
    gyp(2) = rho*temp1
    temp1 = 7.0d0*pr_by_rho + u_sqr
    temp2 = 0.5d0*un*temp1*a2pos
    temp1 = 6.0d0*pr_by_rho + u_sqr
    gyp(4) = rho*(temp2+0.5d0*temp1*b2)
  END SUBROUTINE FLUX_GYP

!  Differentiation of flux_gyn in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: gyn
!   with respect to varying inputs: gyn u1 u2 pr rho
  SUBROUTINE FLUX_GYN_D(gyn, gynd, nx, ny, u1, u1d, u2, u2d, rho, rhod&
&   , pr, prd)
    IMPLICIT NONE
    DOUBLE PRECISION :: gyn(4), u1, u2, rho, pr
    DOUBLE PRECISION :: gynd(4), u1d, u2d, rhod, prd
    DOUBLE PRECISION :: tx, ty, nx, ny, ut, un
    DOUBLE PRECISION :: utd, und
    DOUBLE PRECISION :: beta, s2, b2, a2neg
    DOUBLE PRECISION :: betad, s2d, b2d, a2negd
    DOUBLE PRECISION :: temp1, temp2
    DOUBLE PRECISION :: temp1d, temp2d
    DOUBLE PRECISION :: pr_by_rho, u_sqr
    DOUBLE PRECISION :: pr_by_rhod, u_sqrd
    ! DOUBLE PRECISION :: DERF
    ! DOUBLE PRECISION :: DERF_D
    ! INTRINSIC DSQRT
    ! INTRINSIC DEXP
    ! EXTERNAL DERF
    ! EXTERNAL DERF_D
    DOUBLE PRECISION :: result1
    DOUBLE PRECISION :: result1d
    REAL*8 :: arg1
    REAL*8 :: arg1d
    tx = ny
    ty = -nx
    utd = tx*u1d + ty*u2d
    ut = u1*tx + u2*ty
    und = nx*u1d + ny*u2d
    un = u1*nx + u2*ny
    betad = (0.5d0*rhod*pr-0.5d0*rho*prd)/pr**2
    beta = 0.5d0*rho/pr
    IF (beta .EQ. 0.0) THEN
      result1d = 0.D0
    ELSE
      result1d = betad/(2.D0*DSQRT(beta))
    END IF
    result1 = DSQRT(beta)
    s2d = und*result1 + un*result1d
    s2 = un*result1
    arg1d = pi*betad
    arg1 = pi*beta
    IF (arg1 .EQ. 0.0) THEN
      result1d = 0.D0
    ELSE
      result1d = arg1d/(2.D0*DSQRT(arg1))
    END IF
    result1 = DSQRT(arg1)
    b2d = (-(0.5d0*(s2d*s2+s2*s2d)*DEXP(-(s2*s2))*result1)-0.5d0*DEXP(-(&
&     s2*s2))*result1d)/result1**2
    b2 = 0.5d0*DEXP(-(s2*s2))/result1

    ! result1d = DERF_D(s2, s2d, result1)
    result1d = dexp(-s2**2)*(2.d0/sqrt(pi))*s2d
    result1 = derf(s2)

    a2negd = -(0.5d0*result1d)
    a2neg = 0.5d0*(1.0d0-result1)
    pr_by_rhod = (prd*rho-pr*rhod)/rho**2
    pr_by_rho = pr/rho
    u_sqrd = utd*ut + ut*utd + und*un + un*und
    u_sqr = ut*ut + un*un
!		Expressions for the split fluxes ..
    gynd(1) = rhod*(un*a2neg-b2) + rho*(und*a2neg+un*a2negd-b2d)
    gyn(1) = rho*(un*a2neg-b2)
    temp1d = pr_by_rhod + und*un + un*und
    temp1 = pr_by_rho + un*un
    temp2d = temp1d*a2neg + temp1*a2negd - und*b2 - un*b2d
    temp2 = temp1*a2neg - un*b2
    gynd(3) = rhod*temp2 + rho*temp2d
    gyn(3) = rho*temp2
    temp1d = (utd*un+ut*und)*a2neg + ut*un*a2negd - utd*b2 - ut*b2d
    temp1 = ut*un*a2neg - ut*b2
    gynd(2) = rhod*temp1 + rho*temp1d
    gyn(2) = rho*temp1
    temp1d = 7.0d0*pr_by_rhod + u_sqrd
    temp1 = 7.0d0*pr_by_rho + u_sqr
    temp2d = 0.5d0*((und*temp1+un*temp1d)*a2neg+un*temp1*a2negd)
    temp2 = 0.5d0*un*temp1*a2neg
    temp1d = 6.0d0*pr_by_rhod + u_sqrd
    temp1 = 6.0d0*pr_by_rho + u_sqr
    gynd(4) = rhod*(temp2-0.5d0*temp1*b2) + rho*(temp2d-0.5d0*(temp1d*b2&
&     +temp1*b2d))
    gyn(4) = rho*(temp2-0.5d0*temp1*b2)
  END SUBROUTINE FLUX_GYN_D

  SUBROUTINE FLUX_GYN(gyn, nx, ny, u1, u2, rho, pr)
    IMPLICIT NONE
    DOUBLE PRECISION :: gyn(4), u1, u2, rho, pr
    DOUBLE PRECISION :: tx, ty, nx, ny, ut, un
    DOUBLE PRECISION :: beta, s2, b2, a2neg
    DOUBLE PRECISION :: temp1, temp2
    DOUBLE PRECISION :: pr_by_rho, u_sqr
    ! DOUBLE PRECISION :: DERF
    ! INTRINSIC DSQRT
    ! INTRINSIC DEXP
    ! EXTERNAL DERF
    DOUBLE PRECISION :: result1
    REAL*8 :: arg1
    tx = ny
    ty = -nx
    ut = u1*tx + u2*ty
    un = u1*nx + u2*ny
    beta = 0.5d0*rho/pr
    result1 = DSQRT(beta)
    s2 = un*result1
    arg1 = pi*beta
    result1 = DSQRT(arg1)
    b2 = 0.5d0*DEXP(-(s2*s2))/result1
    result1 = DERF(s2)
    a2neg = 0.5d0*(1.0d0-result1)
    pr_by_rho = pr/rho
    u_sqr = ut*ut + un*un
!		Expressions for the split fluxes ..
    gyn(1) = rho*(un*a2neg-b2)
    temp1 = pr_by_rho + un*un
    temp2 = temp1*a2neg - un*b2
    gyn(3) = rho*temp2
    temp1 = ut*un*a2neg - ut*b2
    gyn(2) = rho*temp1
    temp1 = 7.0d0*pr_by_rho + u_sqr
    temp2 = 0.5d0*un*temp1*a2neg
    temp1 = 6.0d0*pr_by_rho + u_sqr
    gyn(4) = rho*(temp2-0.5d0*temp1*b2)
  END SUBROUTINE FLUX_GYN

END MODULE SPLIT_FLUXES_MOD_DIFF
