!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.14 (r7079) -  5 Oct 2018 09:56
!
!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.14 (r7079) -  5 Oct 2018 09:56
!
MODULE COMPUTE_ENTROPY_MOD_DIFF_DIFF
  USE DATA_STRUCTURE_MOD_DIFF
  IMPLICIT NONE

CONTAINS
!  Differentiation of compute_entropy in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: total_entropy
!   with respect to varying inputs: point.prim
  SUBROUTINE COMPUTE_ENTROPY_D()
    IMPLICIT NONE
    INTEGER :: k
    REAL*8 :: temp1, temp2
    REAL*8 :: temp1d
    INTRINSIC DLOG
    INTRINSIC DABS
    DOUBLE PRECISION :: dabs0
    DOUBLE PRECISION :: dabs0d
    INTRINSIC INT
    total_entropy = 0.d0
    temp2 = DLOG(pr_inf)
    total_entropyd = 0.0_8
    DO k=1,local_points
      IF (point%prim(1, k) .GT. 0.0 .OR. (point%prim(1, k) .LT. 0.0 &
&         .AND. gamma .EQ. INT(gamma))) THEN
        temp1d = gamma*point%prim(1, k)**(gamma-1)*pointd%prim(1, k)
      ELSE IF (point%prim(1, k) .EQ. 0.0 .AND. gamma .EQ. 1.0) THEN
        temp1d = pointd%prim(1, k)
      ELSE
        temp1d = 0.0
      END IF
      temp1 = point%prim(1, k)**gamma
      temp1d = (pointd%prim(4, k)*temp1-point%prim(4, k)*temp1d)/temp1**&
&       2
      temp1 = point%prim(4, k)/temp1
      temp1d = temp1d/temp1
      temp1 = DLOG(temp1)
      IF (temp1 - temp2 .GE. 0.) THEN
        point%entropy(k) = temp1 - temp2
      ELSE
        point%entropy(k) = -(temp1-temp2)
      END IF
      IF (temp1 - temp2 .GE. 0.) THEN
        dabs0d = temp1d
        dabs0 = temp1 - temp2
      ELSE
        dabs0d = -temp1d
        dabs0 = -(temp1-temp2)
      END IF
      total_entropyd = total_entropyd + dabs0d
      total_entropy = total_entropy + dabs0
    END DO
  END SUBROUTINE COMPUTE_ENTROPY_D

  SUBROUTINE COMPUTE_ENTROPY()
    IMPLICIT NONE
    INTEGER :: k
    REAL*8 :: temp1, temp2
    INTRINSIC DLOG
    INTRINSIC DABS
    DOUBLE PRECISION :: dabs0
    total_entropy = 0.d0
    temp2 = DLOG(pr_inf)
    DO k=1,local_points
      temp1 = point%prim(1, k)**gamma
      temp1 = point%prim(4, k)/temp1
      temp1 = DLOG(temp1)
      IF (temp1 - temp2 .GE. 0.) THEN
        point%entropy(k) = temp1 - temp2
      ELSE
        point%entropy(k) = -(temp1-temp2)
      END IF
      IF (temp1 - temp2 .GE. 0.) THEN
        dabs0 = temp1 - temp2
      ELSE
        dabs0 = -(temp1-temp2)
      END IF
      total_entropy = total_entropy + dabs0
    END DO
  END SUBROUTINE COMPUTE_ENTROPY

END MODULE COMPUTE_ENTROPY_MOD_DIFF_DIFF

