!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.14 (r7259) - 18 Jan 2019 09:36
!
MODULE OBJECTIVE_FUNCTION_MOD_DIFF
  USE DATA_STRUCTURE_MOD_DIFF
  USE COMPUTE_FORCE_COEFFS_MOD_DIFF
  USE COMPUTE_ENTROPY_MOD_DIFF
  USE COMPUTE_ENSTROPHY_MOD_DIFF
  USE STAGNATION_VALUES_MOD_DIFF
  IMPLICIT NONE

CONTAINS
!  Differentiation of objective_function in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: *clcd *cd *vector_cost_func
!                *cl *cm *(point.vorticity_sqr)
!   with respect to varying inputs: *clcd *cd *vector_cost_func
!                *cl *cm *(point.x) *(point.y) *(point.nx) *(point.ny)
!                *(point.prim) *(point.vorticity_sqr)
!   Plus diff mem management of: clcd:in cd:in vector_cost_func:in
!                cl:in cm:in point.x:in point.y:in point.nx:in
!                point.ny:in point.prim:in point.vorticity_sqr:in
  SUBROUTINE OBJECTIVE_FUNCTION_D()
    IMPLICIT NONE
    CALL COMPUTE_CL_CD_CM_D()
    CALL COMPUTE_ENTROPY_D()
    CALL COMPUTE_ENSTROPHY_D()
    CALL OBJECTIVE_FUNCTION_J_D()
    vector_cost_funcd = total_loss_stagpressured + cld + cdd + cmd + &
&     clcdd + total_entropyd + total_enstrophyd
    vector_cost_func = total_loss_stagpressure + cl + cd + cm + clcd + &
&     total_entropy + total_enstrophy
    if(rank==0) then
      write(*,*) "Vector function derivative is ", vector_cost_funcd
      write(*,*) "SG", total_loss_stagpressured 
      write(*,*) "Cld", cld
      write(*,*) "Cdd", cdd
      write(*,*) "Cmd", cmd
      write(*,*) "Clcdd", clcdd
      write(*,*) "Entropy", total_entropyd
      write(*,*) "Enstrophyd", total_enstrophyd
      write(*,*) "Vector function is ", vector_cost_func
    end if
  END SUBROUTINE OBJECTIVE_FUNCTION_D

  SUBROUTINE OBJECTIVE_FUNCTION()
    IMPLICIT NONE
    CALL COMPUTE_CL_CD_CM()
    CALL COMPUTE_ENTROPY()
    CALL COMPUTE_ENSTROPHY()
    CALL OBJECTIVE_FUNCTION_J()
    vector_cost_func = total_loss_stagpressure + cl + cd + cm + clcd + &
&     total_entropy + total_enstrophy
  END SUBROUTINE OBJECTIVE_FUNCTION

END MODULE OBJECTIVE_FUNCTION_MOD_DIFF
