!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.14 (r7259) - 18 Jan 2019 09:36
!
MODULE Q_LSKUM_MOD_DIFF
!	First written on 14.10.2016
!	updated on Dec 26, 2016
!	updated on Dec 29, 2016
  USE DATA_STRUCTURE_MOD_DIFF
  USE POINT_NORMALS_MOD_DIFF
  USE GENERATE_CONNECTIVITY_MOD_DIFF
  USE FPI_SOLVER_MOD_DIFF
  USE INITIAL_CONDITIONS_MOD
  IMPLICIT NONE

CONTAINS
!  Differentiation of q_lskum in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: *vector_cost_func
!   with respect to varying inputs: *(point.x) *(point.y)
!   RW status of diff variables: total_enstrophy:(loc) *clcd:(loc)
!                *cd:(loc) *vector_cost_func:out *cl:(loc) *cm:(loc)
!                total_entropy:(loc) *(point.x):in *(point.y):in
!                *(point.nx):(loc) *(point.ny):(loc) *(point.prim):(loc)
!                *(point.prim_old):(loc) *(point.flux_res):(loc)
!                *(point.q):(loc) *(point.dq):(loc) *(point.qm):(loc)
!                *(point.temp):(loc) *(point.vorticity_sqr):(loc)
!                *(point.delta):(loc)
!   Plus diff mem management of: clcd:in cd:in vector_cost_func:in
!                cl:in cm:in point.x:in point.y:in point.nx:in
!                point.ny:in point.prim:in point.prim_old:in point.flux_res:in
!                point.q:in point.dq:in point.qm:in point.temp:in
!                point.vorticity_sqr:in point.delta:in
  SUBROUTINE Q_LSKUM_D()
    IMPLICIT NONE
    INTEGER :: i
    IF (rank .EQ. 0) OPEN(unit=301, file='residue', form='FORMATTED', &
&                   status='REPLACE', action='WRITE') 

    CALL COMPUTE_NORMALS_D()
    CALL GENERATE_CONNECTIVITY()
    IF (rank .EQ. 0) THEN
      WRITE(*, *) 
      WRITE(*, *) '%%%%-Normals and connectivity generated-%%%'
      WRITE(*, *) 
    END IF
! Set U_old to U for first iteration
    DO i=1,local_points
      point%u_old(1, i) = point%prim(1, i)
      point%u_old(2, i) = point%prim(1, i)*point%prim(2, i)
      point%u_old(3, i) = point%prim(1, i)*point%prim(3, i)
      point%u_old(4, i) = 2.5d0*point%prim(4, i) + 0.5d0*point%prim(1, i&
&       )*(point%prim(2, i)*point%prim(2, i)+point%prim(3, i)*point%prim&
&       (3, i))
    END DO
    IF (rank .EQ. 0) THEN
      WRITE(*, *) '%%%%%%%%%%%%%-Iterations begin-%%%%%%%%%%%%'
      WRITE(*, *) 
    END IF
    t = 0.0d0
    IF (restart .EQ. 0) THEN
      itr = 0
    END IF
      IF (ALLOCATED(clcdd)) clcdd = 0.0_8
      IF (ALLOCATED(cdd)) cdd = 0.0_8
      IF (ALLOCATED(vector_cost_funcd)) vector_cost_funcd = 0.0_8
      IF (ALLOCATED(cld)) cld = 0.0_8
      IF (ALLOCATED(cmd)) cmd = 0.0_8
      pointd%prim = 0.0_8
      pointd%prim_old = 0.0_8
      pointd%flux_res = 0.0_8
      pointd%q = 0.0_8
      pointd%dq = 0.0_8
      pointd%qm = 0.0_8
      pointd%temp = 0.0_8
      pointd%vorticity_sqr = 0.0_8
      pointd%delta = 0.0_8
    DO it=itr+1,itr+max_iters
      CALL FPI_SOLVER_D(it)
      t = t + dtg
      IF (rank .EQ. 0) THEN
        IF (timestep .EQ. 0) THEN
          WRITE(*, '(a12,i8,a15,e30.20)') 'iterations:', it, 'residue:'&
&         , residue
          WRITE(301, *) it, residue
        ELSE IF (timestep .EQ. 1) THEN
          WRITE(*, '(a12,i8,a15,e30.20)') 'iterations:', it, 'time:', t
          WRITE(301, *) it, t, dtg
        END IF
      END IF
    END DO
    CLOSE(unit=301) 
  END SUBROUTINE Q_LSKUM_D

END MODULE Q_LSKUM_MOD_DIFF
