1 Command: Command-line option -vars is deprecated: please use -head instead
2 Command: Command-line option -outvars is deprecated: please use -head instead
3 Command: Procedure q_lskum understood as q_lskum_mod.q_lskum
4 q_lskum: (TC19) Equality test on reals is not reliable
5 q_lskum: (AD03) Varied variable residue written by I-O to file 301
6 conserved_vector_ubar: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
7 conserved_vector_ubar: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
8 flux_gxp: (TC33) External procedure derf is not declared
9 flux_gxp: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
10 flux_gxn: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
11 flux_gyp: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
12 flux_gyn: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
13 flux_gxp_d: (TC19) Equality test on reals is not reliable
14 flux_gxp_d: (TC19) Equality test on reals is not reliable
15 flux_gxn_d: (TC19) Equality test on reals is not reliable
16 flux_gxn_d: (TC19) Equality test on reals is not reliable
17 flux_gyp_d: (TC19) Equality test on reals is not reliable
18 flux_gyp_d: (TC19) Equality test on reals is not reliable
19 flux_gyn_d: (TC19) Equality test on reals is not reliable
20 flux_gyn_d: (TC19) Equality test on reals is not reliable
21 flux_quad_gxi: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
22 flux_quad_gxi: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
23 flux_quad_gxii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
24 flux_quad_gxii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
25 flux_quad_gxiii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
26 flux_quad_gxiii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
27 flux_quad_gxiv: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
28 flux_quad_gxiv: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
29 flux_quad_gxi_d: (TC19) Equality test on reals is not reliable
30 flux_quad_gxi_d: (TC19) Equality test on reals is not reliable
31 flux_quad_gxi_d: (TC19) Equality test on reals is not reliable
32 flux_quad_gxi_d: (TC19) Equality test on reals is not reliable
33 flux_quad_gxii_d: (TC19) Equality test on reals is not reliable
34 flux_quad_gxii_d: (TC19) Equality test on reals is not reliable
35 flux_quad_gxii_d: (TC19) Equality test on reals is not reliable
36 flux_quad_gxii_d: (TC19) Equality test on reals is not reliable
37 flux_quad_gxiii_d: (TC19) Equality test on reals is not reliable
38 flux_quad_gxiii_d: (TC19) Equality test on reals is not reliable
39 flux_quad_gxiii_d: (TC19) Equality test on reals is not reliable
40 flux_quad_gxiii_d: (TC19) Equality test on reals is not reliable
41 flux_quad_gxiv_d: (TC19) Equality test on reals is not reliable
42 flux_quad_gxiv_d: (TC19) Equality test on reals is not reliable
43 flux_quad_gxiv_d: (TC19) Equality test on reals is not reliable
44 flux_quad_gxiv_d: (TC19) Equality test on reals is not reliable
45 (DF05) External routine derf, called by (flux_gxp flux_gxn flux_gyp flux_gyn flux_gxp_d flux_gxn_d flux_gyp_d flux_gyn_d conserved_vector_ubar flux_quad_gxi flux_quad_gxii flux_quad_gxiii flux_quad_gxiv flux_quad_gxi_d flux_quad_gxii_d flux_quad_gxiii_d flux_quad_gxiv_d), is assumed default In:.1. and Out:.11
46 data_structure_mod: (DD28) Save statement may save extra variables, please use "save::varname" 
