!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.14 (r7259) - 18 Jan 2019 09:36
!
MODULE COMPUTE_ENTROPY_MOD_DIFF
#include <petsc/finclude/petscsys.h>
    USE DATA_STRUCTURE_MOD_DIFF
    USE PETSC_DATA_STRUCTURE_MOD
    IMPLICIT NONE
    
    CONTAINS
    SUBROUTINE COMPUTE_ENTROPY()
        IMPLICIT NONE
        INTEGER :: k
        REAL*8 :: temp1, temp2
        REAL*8 :: gtotal_entropy
        INTRINSIC DLOG
        PetscErrorCode :: ierr
        total_entropy = 0.d0
        temp2 = DLOG(pr_inf)
        DO k=1,local_points
            temp1 = point%prim(1, k)**gamma
            temp1 = point%prim(4, k)/temp1
            temp1 = DLOG(temp1)
            point%entropy(k) = (temp1-temp2)**2
            total_entropy = total_entropy + (temp1-temp2)**2
        END DO
        CALL MPI_REDUCE(total_entropy, gtotal_entropy, 1, mpi_double, &
        &             mpi_sum, 0, petsc_comm_world, ierr)
        IF (rank .EQ. 0) WRITE(*, *) 'total entropy :', gtotal_entropy
    END SUBROUTINE COMPUTE_ENTROPY
    
    !  Differentiation of compute_enstrophy in reverse (adjoint) mode (with options fixinterface):
    !   gradient     of useful results: total_enstrophy *(point.prim)
    !                *(point.vorticity_sqr)
    !   with respect to varying inputs: *(point.prim) *(point.vorticity_sqr)
    !   Plus diff mem management of: point.prim:in point.vorticity_sqr:in
    SUBROUTINE COMPUTE_ENSTROPHY_B()
        IMPLICIT NONE
        INTEGER :: i, k, r, nbh
        REAL*8 :: x_i, y_i, x_k, y_k
        REAL*8 :: delx, dely, dist, weights
        REAL*8 :: sum_delx_sqr, sum_dely_sqr, sum_delx_dely
        REAL*8 :: sum_delx_delu1, sum_delx_delu2, sum_dely_delu1, &
        &   sum_dely_delu2
        REAL*8 :: sum_delx_delu1b, sum_delx_delu2b, sum_dely_delu1b, &
        &   sum_dely_delu2b
        REAL*8 :: sum_delx_sqr_delu1_sqr, sum_delx_sqr_delu2_sqr, &
        &   sum_dely_sqr_delu1_sqr, sum_dely_sqr_delu2_sqr
        REAL*8 :: det
        REAL*8 :: one_by_det
        REAL*8 :: du1_dy, du2_dx, temp, du1_sqr_dx_sqr, du2_sqr_dy_sqr, &
        &   du1_dx, du2_dy
        REAL*8 :: du1_dyb, du2_dxb, du1_dxb, du2_dyb
        REAL*8 :: gtotal_enstrophy
        INTRINSIC DSQRT
        REAL*8 :: tempb
        REAL*8 :: tempb0
        REAL*8 :: tempb1
        REAL*8 :: tempb2
        REAL*8 :: tempb3
        INTEGER :: ad_to
        PetscErrorCode :: ierr
        total_enstrophy = 0.d0
        DO i=1,local_points
            x_i = point%x(i)
            y_i = point%y(i)
            CALL PUSHREAL8(sum_delx_sqr)
            sum_delx_sqr = 0.d0
            CALL PUSHREAL8(sum_dely_sqr)
            sum_dely_sqr = 0.d0
            CALL PUSHREAL8(sum_delx_dely)
            sum_delx_dely = 0.d0
            sum_delx_delu1 = 0.d0
            sum_dely_delu1 = 0.d0
            sum_delx_delu2 = 0.d0
            sum_dely_delu2 = 0.d0
            DO k=1,point%nbhs(i)
                nbh = point%conn(i, k)
                x_k = point%x(nbh)
                y_k = point%y(nbh)
                delx = x_k - x_i
                dely = y_k - y_i
                dist = DSQRT(delx*delx + dely*dely)
                CALL PUSHREAL8(weights)
                weights = dist**power
                sum_delx_sqr = sum_delx_sqr + delx*delx*weights
                sum_dely_sqr = sum_dely_sqr + dely*dely*weights
                sum_delx_dely = sum_delx_dely + delx*dely*weights
                sum_delx_delu1 = sum_delx_delu1 + weights*delx*(point%prim(2, &
                &         nbh)-point%prim(2, i))
                sum_delx_delu2 = sum_delx_delu2 + weights*delx*(point%prim(3, &
                &         nbh)-point%prim(3, i))
                sum_dely_delu1 = sum_dely_delu1 + weights*dely*(point%prim(2, &
                &         nbh)-point%prim(2, i))
                sum_dely_delu2 = sum_dely_delu2 + weights*dely*(point%prim(3, &
                &         nbh)-point%prim(3, i))
            END DO
            CALL PUSHINTEGER4(k - 1)
            det = sum_delx_sqr*sum_dely_sqr - sum_delx_dely*sum_delx_dely
            CALL PUSHREAL8(one_by_det)
            one_by_det = 1.0d0/det
            CALL PUSHREAL8(du2_dx)
            du2_dx = (sum_delx_delu2*sum_dely_sqr-sum_dely_delu2*sum_delx_dely&
            &       )*one_by_det
            CALL PUSHREAL8(du1_dy)
            du1_dy = (sum_dely_delu1*sum_delx_sqr-sum_delx_delu1*sum_delx_dely&
            &       )*one_by_det
            CALL PUSHREAL8(du2_dy)
            du2_dy = (sum_dely_delu2*sum_delx_sqr-sum_delx_delu2*sum_delx_dely&
            &       )*one_by_det
            CALL PUSHREAL8(du1_dx)
            du1_dx = (sum_delx_delu1*sum_dely_sqr-sum_dely_delu1*sum_delx_dely&
            &       )*one_by_det
            total_enstrophy = total_enstrophy + (du1_dx*du1_dx+du2_dx*du2_dx+&
            &       du1_dy*du1_dy+du2_dy*du2_dy)*point%vor_area(i)
        END DO
        CALL MPI_REDUCE(total_enstrophy, gtotal_enstrophy, 1, mpi_double, &
        &             mpi_sum, 0, petsc_comm_world, ierr)
        DO i=local_points,1,-1
            tempb3 = point%vor_area(i)*total_enstrophyb
            du1_dxb = 2*du1_dx*tempb3
            du2_dxb = 2*du2_dx*tempb3
            du1_dyb = 2*du1_dy*tempb3
            du2_dyb = 2*du2_dy*tempb3
            CALL POPREAL8(du1_dx)
            sum_delx_delu1b = one_by_det*sum_dely_sqr*du1_dxb - one_by_det*&
            &       sum_delx_dely*du1_dyb
            sum_dely_delu1b = one_by_det*sum_delx_sqr*du1_dyb - one_by_det*&
            &       sum_delx_dely*du1_dxb
            CALL POPREAL8(du2_dy)
            sum_dely_delu2b = one_by_det*sum_delx_sqr*du2_dyb - one_by_det*&
            &       sum_delx_dely*du2_dxb
            sum_delx_delu2b = one_by_det*sum_dely_sqr*du2_dxb - one_by_det*&
            &       sum_delx_dely*du2_dyb
            CALL POPREAL8(du1_dy)
            CALL POPREAL8(du2_dx)
            CALL POPREAL8(one_by_det)
            y_i = point%y(i)
            x_i = point%x(i)
            CALL POPINTEGER4(ad_to)
            DO k=ad_to,1,-1
                nbh = point%conn(i, k)
                y_k = point%y(nbh)
                dely = y_k - y_i
                tempb = weights*dely*sum_dely_delu2b
                pointb%prim(3, nbh) = pointb%prim(3, nbh) + tempb
                pointb%prim(3, i) = pointb%prim(3, i) - tempb
                tempb0 = weights*dely*sum_dely_delu1b
                pointb%prim(2, nbh) = pointb%prim(2, nbh) + tempb0
                pointb%prim(2, i) = pointb%prim(2, i) - tempb0
                x_k = point%x(nbh)
                delx = x_k - x_i
                tempb1 = weights*delx*sum_delx_delu2b
                pointb%prim(3, nbh) = pointb%prim(3, nbh) + tempb1
                pointb%prim(3, i) = pointb%prim(3, i) - tempb1
                tempb2 = weights*delx*sum_delx_delu1b
                pointb%prim(2, nbh) = pointb%prim(2, nbh) + tempb2
                pointb%prim(2, i) = pointb%prim(2, i) - tempb2
                CALL POPREAL8(weights)
            END DO
            CALL POPREAL8(sum_delx_dely)
            CALL POPREAL8(sum_dely_sqr)
            CALL POPREAL8(sum_delx_sqr)
        END DO
    END SUBROUTINE COMPUTE_ENSTROPHY_B
    
    SUBROUTINE COMPUTE_ENSTROPHY()
        IMPLICIT NONE
        INTEGER :: i, k, r, nbh
        REAL*8 :: x_i, y_i, x_k, y_k
        REAL*8 :: delx, dely, dist, weights
        REAL*8 :: sum_delx_sqr, sum_dely_sqr, sum_delx_dely
        REAL*8 :: sum_delx_delu1, sum_delx_delu2, sum_dely_delu1, &
        &   sum_dely_delu2
            REAL*8 :: sum_delx_sqr_delu1_sqr, sum_delx_sqr_delu2_sqr, &
        &   sum_dely_sqr_delu1_sqr, sum_dely_sqr_delu2_sqr
            REAL*8 :: det
            REAL*8 :: one_by_det
            REAL*8 :: du1_dy, du2_dx, temp, du1_sqr_dx_sqr, du2_sqr_dy_sqr, &
        &   du1_dx, du2_dy
            REAL*8 :: gtotal_enstrophy
            INTRINSIC DSQRT
        PetscErrorCode :: ierr
        total_enstrophy = 0.d0
        DO i=1,local_points
            x_i = point%x(i)
            y_i = point%y(i)
            sum_delx_sqr = 0.d0
            sum_dely_sqr = 0.d0
            sum_delx_dely = 0.d0
            sum_delx_delu1 = 0.d0
            sum_dely_delu1 = 0.d0
            sum_delx_delu2 = 0.d0
            sum_dely_delu2 = 0.d0
            DO k=1,point%nbhs(i)
                nbh = point%conn(i, k)
                x_k = point%x(nbh)
                y_k = point%y(nbh)
                delx = x_k - x_i
                dely = y_k - y_i
                dist = DSQRT(delx*delx + dely*dely)
                weights = dist**power
                sum_delx_sqr = sum_delx_sqr + delx*delx*weights
                sum_dely_sqr = sum_dely_sqr + dely*dely*weights
                sum_delx_dely = sum_delx_dely + delx*dely*weights
                sum_delx_delu1 = sum_delx_delu1 + weights*delx*(point%prim(2, &
                &         nbh)-point%prim(2, i))
                sum_delx_delu2 = sum_delx_delu2 + weights*delx*(point%prim(3, &
                &         nbh)-point%prim(3, i))
                sum_dely_delu1 = sum_dely_delu1 + weights*dely*(point%prim(2, &
                &         nbh)-point%prim(2, i))
                sum_dely_delu2 = sum_dely_delu2 + weights*dely*(point%prim(3, &
                &         nbh)-point%prim(3, i))
            END DO
            det = sum_delx_sqr*sum_dely_sqr - sum_delx_dely*sum_delx_dely
            one_by_det = 1.0d0/det
            du2_dx = (sum_delx_delu2*sum_dely_sqr-sum_dely_delu2*sum_delx_dely&
            &       )*one_by_det
            du1_dy = (sum_dely_delu1*sum_delx_sqr-sum_delx_delu1*sum_delx_dely&
            &       )*one_by_det
                  du2_dy = (sum_dely_delu2*sum_delx_sqr-sum_delx_delu2*sum_delx_dely&
            &       )*one_by_det
                  du1_dx = (sum_delx_delu1*sum_dely_sqr-sum_dely_delu1*sum_delx_dely&
            &       )*one_by_det
                  total_enstrophy = total_enstrophy + (du1_dx*du1_dx+du2_dx*du2_dx+&
            &       du1_dy*du1_dy+du2_dy*du2_dy)*point%vor_area(i)
        END DO
        CALL MPI_REDUCE(total_enstrophy, gtotal_enstrophy, 1, mpi_double, &
        &             mpi_sum, 0, petsc_comm_world, ierr)
        IF (rank .EQ. 0) WRITE(*, *) 'total enstrophy :', gtotal_enstrophy
    END SUBROUTINE COMPUTE_ENSTROPHY
    
END MODULE COMPUTE_ENTROPY_MOD_DIFF
