!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.14 (r7259) - 18 Jan 2019 09:36
!
MODULE FPI_SOLVER_MOD_DIFF
  USE DATA_STRUCTURE_MOD_DIFF
  USE FLUX_RESIDUAL_MOD_DIFF
  USE STATE_UPDATE_MOD_DIFF
  USE Q_VARIABLES_MOD_DIFF
  USE OBJECTIVE_FUNCTION_MOD_DIFF
  USE STAGNATION_VALUES_MOD_DIFF
  IMPLICIT NONE

CONTAINS
!  Differentiation of fpi_solver in reverse (adjoint) mode (with options fixinterface):
!   gradient     of useful results: cost_func point.delta point.prim
!                point.prim_old point.q point.flux_res point.dq
!                point.ddq point.temp point.phi1 point.phi2
!   with respect to varying inputs: point.delta point.prim point.prim_old
!                point.q point.flux_res point.dq point.ddq point.temp
!                point.phi1 point.phi2
  SUBROUTINE FPI_SOLVER_B(t)
    IMPLICIT NONE
    INTEGER :: t, i, rk, ierr
    INTRINSIC DSQRT
    INTRINSIC DLOG10
    INTEGER :: branch
    DO i=1,max_points
      point%prim_old(:, i) = point%prim(:, i)
    END DO
    CALL FUNC_DELTA()
! Perform 4-stage, 3-order SSPRK update
    DO rk=1,rks
      CALL PUSHREAL8ARRAY(point%q, 4*max_points)
      CALL EVAL_Q_VARIABLES()
      CALL PUSHREAL8ARRAY(point%dq, 2*4*max_points)
      CALL EVAL_Q_DERIVATIVES()
      CALL PUSHREAL8ARRAY(point%ddq, 3*4*max_points)
      CALL EVAL_Q_DOUBLE_DERIVATIVES()
      IF (inner_iterations .NE. 0) THEN
        DO i=1,inner_iterations
          CALL EVAL_DQ_INNER_LOOP()
          CALL EVAL_UPDATE_INNERLOOP_2()
          CALL EVAL_DDQ_INNER_LOOP()
          CALL EVAL_UPDATE_INNERLOOP_3()
        END DO
        CALL PUSHCONTROL1B(0)
      ELSE
        CALL PUSHCONTROL1B(1)
      END IF
      CALL PUSHREAL8ARRAY(point%flux_res, 4*max_points)
      CALL CAL_FLUX_RESIDUAL()
      CALL PUSHREAL8ARRAY(point%prim, 4*max_points)
      CALL STATE_UPDATE(rk)
    END DO
    CALL OBJECTIVE_FUNCTION_J_B()
    DO rk=rks,1,-1
      CALL POPREAL8ARRAY(point%prim, 4*max_points)
      CALL STATE_UPDATE_B(rk)
      CALL POPREAL8ARRAY(point%flux_res, 4*max_points)
      CALL CAL_FLUX_RESIDUAL_B()
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        DO i=inner_iterations,1,-1
          CALL EVAL_UPDATE_INNERLOOP_3_B()
          CALL EVAL_DDQ_INNER_LOOP_B()
          CALL EVAL_UPDATE_INNERLOOP_2_B()
          CALL EVAL_DQ_INNER_LOOP_B()
        END DO
      END IF
      CALL POPREAL8ARRAY(point%ddq, 3*4*max_points)
      CALL EVAL_Q_DOUBLE_DERIVATIVES_B()
      CALL POPREAL8ARRAY(point%dq, 2*4*max_points)
      CALL EVAL_Q_DERIVATIVES_B()
      CALL POPREAL8ARRAY(point%q, 4*max_points)
      CALL EVAL_Q_VARIABLES_B()
    END DO
    CALL FUNC_DELTA_B()
    DO i=max_points,1,-1
      pointb%prim(:, i) = pointb%prim(:, i) + pointb%prim_old(:, i)
      pointb%prim_old(:, i) = 0.0_8
    END DO
  END SUBROUTINE FPI_SOLVER_B

  SUBROUTINE FPI_SOLVER(t)
    IMPLICIT NONE
    INTEGER :: t, i, rk, ierr
    INTRINSIC DSQRT
    INTRINSIC DLOG10
    DO i=1,max_points
      point%prim_old(:, i) = point%prim(:, i)
    END DO
    CALL FUNC_DELTA()
! Perform 4-stage, 3-order SSPRK update
    DO rk=1,rks
      CALL EVAL_Q_VARIABLES()
      CALL EVAL_Q_DERIVATIVES()
      CALL EVAL_Q_DOUBLE_DERIVATIVES()
      IF (inner_iterations .NE. 0) THEN
        DO i=1,inner_iterations
          CALL EVAL_DQ_INNER_LOOP()
          CALL EVAL_UPDATE_INNERLOOP_2()
          CALL EVAL_DDQ_INNER_LOOP()
          CALL EVAL_UPDATE_INNERLOOP_3()
        END DO
      END IF
      CALL CAL_FLUX_RESIDUAL()
      CALL STATE_UPDATE(rk)
    END DO
    CALL OBJECTIVE_FUNCTION()
    CALL STAGNATION_PRESSURE()
    CALL OBJECTIVE_FUNCTION_J()
    res_new = DSQRT(sum_res_sqr)/max_points
    IF (t .LE. 2 .AND. restart .EQ. 0) THEN
      res_old = res_new
      residue = 0.d0
    ELSE
      residue = DLOG10(res_new/res_old)
    END IF
  END SUBROUTINE FPI_SOLVER

END MODULE FPI_SOLVER_MOD_DIFF

