!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.14 (r7259) - 18 Jan 2019 09:36
!
MODULE Q_LSKUM_MOD_DIFF
!	First written on 14.10.2016
!	updated on Dec 26, 2016
!	updated on Dec 29, 2016
  USE DATA_STRUCTURE_MOD_DIFF
  USE POINT_NORMALS_MOD_DIFF
  USE GENERATE_CONNECTIVITY_MOD_DIFF
  USE FPI_SOLVER_MOD_DIFF
  IMPLICIT NONE

CONTAINS
!  Differentiation of q_lskum in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: cost_func
!   with respect to varying inputs: *(point.phi1) *(point.phi2)
!   RW status of diff variables: cost_func:out *(point.delta):(loc)
!                *(point.prim):(loc) *(point.prim_old):(loc) *(point.q):(loc)
!                *(point.flux_res):(loc) *(point.dq):(loc) *(point.ddq):(loc)
!                *(point.temp):(loc) *(point.phi1):in-killed *(point.phi2):in-killed
!   Plus diff mem management of: point.delta:in point.prim:in point.prim_old:in
!                point.q:in point.flux_res:in point.dq:in point.ddq:in
!                point.temp:in point.phi1:in point.phi2:in
  SUBROUTINE Q_LSKUM_D()
    IMPLICIT NONE
    INTEGER :: i
    OPEN(unit=301, file='residue', form='FORMATTED', status='REPLACE', &
&  action='WRITE') 
    CALL COMPUTE_NORMALS()
    CALL GENERATE_CONNECTIVITY()
    WRITE(*, *) '%%%%-Normals and connectivity generated-%%%'
    WRITE(*, *) 
    DO i=1,max_points
      pointd%phi1(:, i) = 0.0_8
      point%phi1(:, i) = 1.0d0
      pointd%phi2(:, i) = 0.0_8
      point%phi2(:, i) = 1.0d0
    END DO
! point%phi1(80,1) = point%phi1(80,1) + 1e-3
    WRITE(*, *) '%%%%%%%%%%%%%-Iterations begin-%%%%%%%%%%%%'
    WRITE(*, *) 
    IF (restart .EQ. 0) THEN
      itr = 0
      cost_funcd = 0.0_8
      pointd%delta = 0.0_8
      pointd%prim = 0.0_8
      pointd%prim_old = 0.0_8
      pointd%q = 0.0_8
      pointd%flux_res = 0.0_8
      pointd%dq = 0.0_8
      pointd%ddq = 0.0_8
      pointd%temp = 0.0_8
    ELSE
      cost_funcd = 0.0_8
      pointd%delta = 0.0_8
      pointd%prim = 0.0_8
      pointd%prim_old = 0.0_8
      pointd%q = 0.0_8
      pointd%flux_res = 0.0_8
      pointd%dq = 0.0_8
      pointd%ddq = 0.0_8
      pointd%temp = 0.0_8
    END IF
    DO it=itr+1,itr+max_iters
      CALL FPI_SOLVER_D(it)
      WRITE(*, '(a12,i8,a15,e30.20)') 'iterations:', it, 'residue:', &
&     residue
      WRITE(301, *) it, residue
      IF (residue .NE. residue) EXIT
    END DO
    CLOSE(unit=301) 
  END SUBROUTINE Q_LSKUM_D

  SUBROUTINE Q_LSKUM()
    IMPLICIT NONE
    INTEGER :: i
    OPEN(unit=301, file='residue', form='FORMATTED', status='REPLACE', &
&  action='WRITE') 
    CALL COMPUTE_NORMALS()
    CALL GENERATE_CONNECTIVITY()
    WRITE(*, *) '%%%%-Normals and connectivity generated-%%%'
    WRITE(*, *) 
    DO i=1,max_points
      point%phi1(:, i) = 1.0d0
      point%phi2(:, i) = 1.0d0
    END DO
! point%phi1(80,1) = point%phi1(80,1) + 1e-3
    WRITE(*, *) '%%%%%%%%%%%%%-Iterations begin-%%%%%%%%%%%%'
    WRITE(*, *) 
    IF (restart .EQ. 0) itr = 0
    DO it=itr+1,itr+max_iters
      CALL FPI_SOLVER(it)
      WRITE(*, '(a12,i8,a15,e30.20)') 'iterations:', it, 'residue:', &
&     residue
      WRITE(301, *) it, residue
      IF (residue .NE. residue) GOTO 100
    END DO
 100 CLOSE(unit=301) 
  END SUBROUTINE Q_LSKUM

END MODULE Q_LSKUM_MOD_DIFF

