1 Command: Command-line option -vars is deprecated: please use -head instead
2 Command: Command-line option -outvars is deprecated: please use -head instead
3 Command: Procedure q_lskum understood as q_lskum_mod.q_lskum
4 q_lskum_mod: (DD15) Module initial_conditions_mod is not defined
5 q_lskum_mod: (DD15) Module ieee_arithmetic is not defined
6 q_lskum: (TC20) Variable rank is not declared
7 q_lskum: (TC33) External procedure ieee_is_nan is not declared
8 q_lskum: (DF03) variable rank is used before initialized
9 q_lskum: (DF03) variable rank is used before initialized
10 q_lskum: (DF03) variable rank is used before initialized
11 q_lskum: (DF03) variable rank is used before initialized
12 q_lskum: (AD03) Varied variable residue written by I-O to file 301
13 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%delta
14 q_lskum: (AD12) User help requested: unknown dimension 3 of array *point%temp
15 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%temp
16 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%temp
17 q_lskum: (AD12) User help requested: unknown dimension 3 of array *point%ddq
18 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%ddq
19 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%ddq
20 q_lskum: (AD12) User help requested: unknown dimension 3 of array *point%qm
21 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%qm
22 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%qm
23 q_lskum: (AD12) User help requested: unknown dimension 3 of array *point%dq
24 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%dq
25 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%dq
26 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%q
27 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%q
28 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%flux_res
29 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%flux_res
30 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%prim_old
31 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%prim_old
32 q_lskum: (AD12) User help requested: unknown dimension 2 of array *point%prim
33 q_lskum: (AD12) User help requested: unknown dimension 1 of array *point%prim
34 (DF05) External routine ieee_is_nan, called by (q_lskum), is assumed default In:.1. and Out:.11
35 fpi_solver_mod: (DD15) Module post_processing_mod is not defined
36 fpi_solver: (TC33) External procedure update_begin_dq_ghost is not declared
37 fpi_solver: (TC33) External procedure update_begin_qm_ghost is not declared
38 fpi_solver: (TC33) External procedure update_end_dq_ghost is not declared
39 fpi_solver: (TC33) External procedure update_end_qm_ghost is not declared
40 fpi_solver: (TC33) External procedure update_begin_ddq_ghost is not declared
41 fpi_solver: (TC33) External procedure update_end_ddq_ghost is not declared
42 fpi_solver: (TC33) External procedure update_begin_prim_ghost is not declared
43 fpi_solver: (TC33) External procedure update_end_prim_ghost is not declared
44 fpi_solver: (TC20) Variable mpi_double is not declared
45 fpi_solver: (TC20) Variable mpi_sum is not declared
46 fpi_solver: (TC20) Variable petsc_comm_world is not declared
47 fpi_solver: (TC20) Variable ierr is not declared
48 fpi_solver: (TC20) Variable rank is not declared
49 fpi_solver: (TC33) External procedure print_primal_output is not declared
50 fpi_solver: (DF03) variable rank is used before initialized
51 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%q
52 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%q
53 fpi_solver: (AD12) User help requested: unknown dimension 3 of array *point%dq
54 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%dq
55 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%dq
56 fpi_solver: (AD12) User help requested: unknown dimension 3 of array *point%ddq
57 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%ddq
58 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%ddq
59 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%flux_res
60 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%flux_res
61 fpi_solver: (AD12) User help requested: unknown dimension 2 of array *point%prim
62 fpi_solver: (AD12) User help requested: unknown dimension 1 of array *point%prim
63 (DF05) External routine print_primal_output, called by (fpi_solver), is assumed default In:. and Out:.
64 (DF05) External routine update_end_prim_ghost, called by (fpi_solver), is assumed default In:. and Out:.
65 (DF05) External routine update_begin_prim_ghost, called by (fpi_solver), is assumed default In:. and Out:.
66 (DF05) External routine update_end_ddq_ghost, called by (fpi_solver), is assumed default In:. and Out:.
67 (DF05) External routine update_begin_ddq_ghost, called by (fpi_solver), is assumed default In:. and Out:.
68 (DF05) External routine update_end_qm_ghost, called by (fpi_solver), is assumed default In:. and Out:.
69 (DF05) External routine update_end_dq_ghost, called by (fpi_solver), is assumed default In:. and Out:.
70 (DF05) External routine update_begin_qm_ghost, called by (fpi_solver), is assumed default In:. and Out:.
71 (DF05) External routine update_begin_dq_ghost, called by (fpi_solver), is assumed default In:. and Out:.
72 state_update_mod: (DD15) Module petsc_data_structure_mod is not defined
73 cal_flux_residual: (AD12) User help requested: unknown dimension 1 of array *point%flux_res
74 cal_flux_residual: (AD12) User help requested: unknown dimension 1 of array *point%flux_res
75 conserved_vector_ubar: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
76 conserved_vector_ubar: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
77 generate_connectivity_mod: (DD15) Module petsc_data_structure_mod is not defined
78 get_interior_neighbours: (TC20) Variable rank is not declared
79 get_interior_neighbours: (DF03) variable rank is used before initialized
80 get_interior_neighbours: (DF03) variable rank is used before initialized
81 get_interior_neighbours: (DF03) variable rank is used before initialized
82 get_interior_neighbours: (DF03) variable rank is used before initialized
83 get_wall_boundary_neighbours: (TC20) Variable rank is not declared
84 get_wall_boundary_neighbours: (DF03) variable rank is used before initialized
85 get_wall_boundary_neighbours: (DF03) variable rank is used before initialized
86 get_wall_boundary_neighbours: (DF03) variable rank is used before initialized
87 get_outer_boundary_neighbours: (TC20) Variable rank is not declared
88 get_outer_boundary_neighbours: (DF03) variable rank is used before initialized
89 get_outer_boundary_neighbours: (DF03) variable rank is used before initialized
90 get_outer_boundary_neighbours: (DF03) variable rank is used before initialized
91 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
92 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
93 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
94 interior_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
95 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
96 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
97 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
98 interior_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
99 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
100 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
101 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
102 interior_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
103 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
104 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
105 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
106 interior_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
107 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
108 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
109 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
110 wall_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
111 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
112 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
113 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
114 wall_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
115 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
116 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
117 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
118 wall_dgy_neg: (AD12) User help requested: unknown dimension 1 of array temp
119 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
120 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
121 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
122 outer_dgx_pos: (AD12) User help requested: unknown dimension 1 of array temp
123 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
124 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
125 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
126 outer_dgx_neg: (AD12) User help requested: unknown dimension 1 of array temp
127 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
128 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
129 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
130 outer_dgy_pos: (AD12) User help requested: unknown dimension 1 of array temp
131 eval_q_derivatives: (AD12) User help requested: unknown dimension 1 of array temp
132 eval_q_derivatives: (AD12) User help requested: unknown dimension 1 of array temp
133 eval_q_double_derivatives: (AD12) User help requested: unknown dimension 1 of array temp
134 eval_q_double_derivatives: (AD12) User help requested: unknown dimension 1 of array temp
135 eval_q_double_derivatives: (AD12) User help requested: unknown dimension 1 of array temp
136 eval_q_double_derivatives: (AD12) User help requested: unknown dimension 1 of array temp
137 flux_gxp: (TC33) External procedure derf is not declared
138 flux_gxp: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
139 flux_gxn: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
140 flux_gyp: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
141 flux_gyn: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
142 flux_gxp_d: (TC19) Equality test on reals is not reliable
143 flux_gxp_d: (TC19) Equality test on reals is not reliable
144 flux_gxn_d: (TC19) Equality test on reals is not reliable
145 flux_gxn_d: (TC19) Equality test on reals is not reliable
146 flux_gyp_d: (TC19) Equality test on reals is not reliable
147 flux_gyp_d: (TC19) Equality test on reals is not reliable
148 flux_gyn_d: (TC19) Equality test on reals is not reliable
149 flux_gyn_d: (TC19) Equality test on reals is not reliable
150 flux_quad_gxi: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
151 flux_quad_gxi: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
152 flux_quad_gxii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
153 flux_quad_gxii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
154 flux_quad_gxiii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
155 flux_quad_gxiii: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
156 flux_quad_gxiv: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
157 flux_quad_gxiv: (AD09) Please provide a differential of function derf for arguments Arg1=(in) Result=(out)
158 flux_quad_gxi_d: (TC19) Equality test on reals is not reliable
159 flux_quad_gxi_d: (TC19) Equality test on reals is not reliable
160 flux_quad_gxi_d: (TC19) Equality test on reals is not reliable
161 flux_quad_gxi_d: (TC19) Equality test on reals is not reliable
162 flux_quad_gxii_d: (TC19) Equality test on reals is not reliable
163 flux_quad_gxii_d: (TC19) Equality test on reals is not reliable
164 flux_quad_gxii_d: (TC19) Equality test on reals is not reliable
165 flux_quad_gxii_d: (TC19) Equality test on reals is not reliable
166 flux_quad_gxiii_d: (TC19) Equality test on reals is not reliable
167 flux_quad_gxiii_d: (TC19) Equality test on reals is not reliable
168 flux_quad_gxiii_d: (TC19) Equality test on reals is not reliable
169 flux_quad_gxiii_d: (TC19) Equality test on reals is not reliable
170 flux_quad_gxiv_d: (TC19) Equality test on reals is not reliable
171 flux_quad_gxiv_d: (TC19) Equality test on reals is not reliable
172 flux_quad_gxiv_d: (TC19) Equality test on reals is not reliable
173 flux_quad_gxiv_d: (TC19) Equality test on reals is not reliable
174 (DF05) External routine derf, called by (flux_gxp flux_gxn flux_gyp flux_gyn flux_gxp_d flux_gxn_d flux_gyp_d flux_gyn_d conserved_vector_ubar flux_quad_gxi flux_quad_gxii flux_quad_gxiii flux_quad_gxiv flux_quad_gxi_d flux_quad_gxii_d flux_quad_gxiii_d flux_quad_gxiv_d), is assumed default In:.1. and Out:.11
175 compute_force_coeffs_mod: (DD15) Module petsc_data_structure_mod is not defined
176 compute_cl_cd_cm: (TC20) Variable proc is not declared
177 compute_cl_cd_cm: (TC24) Wrong number of dimensions for array itos: 1 expected, and 2 given
178 compute_cl_cd_cm: (TC20) Variable rank is not declared
179 compute_cl_cd_cm: (TC20) Variable mpi_double is not declared
180 compute_cl_cd_cm: (TC20) Variable mpi_sum is not declared
181 compute_cl_cd_cm: (TC20) Variable petsc_comm_world is not declared
182 compute_cl_cd_cm: (TC20) Variable ierr is not declared
183 compute_entropy_mod: (DD15) Module petsc_data_structure_mod is not defined
184 compute_entropy: (TC20) Variable mpi_double is not declared
185 compute_entropy: (TC20) Variable mpi_sum is not declared
186 compute_entropy: (TC20) Variable petsc_comm_world is not declared
187 compute_entropy: (TC20) Variable ierr is not declared
188 stagnation_values_mod: (DD15) Module petsc_data_structure_mod is not defined
189 data_structure_mod: (DD28) Save statement may save extra variables, please use "save::varname" 
190 objective_function_j: (TC20) Variable mpi_double is not declared
191 objective_function_j: (TC20) Variable mpi_sum is not declared
192 objective_function_j: (TC20) Variable petsc_comm_world is not declared
193 objective_function_j: (TC20) Variable ierr is not declared
194 objective_function_j: (TC20) Variable rank is not declared
195 objective_function_j: (DF03) variable rank is used before initialized
196 get_interior_neighbours: Tool: (TypeSpec tree regeneration) null wrapped type
197 get_wall_boundary_neighbours: Tool: (TypeSpec tree regeneration) null wrapped type
198 get_outer_boundary_neighbours: Tool: (TypeSpec tree regeneration) null wrapped type
199 compute_cl_cd_cm: Tool: (TypeSpec tree regeneration) null wrapped type
